"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"
import { useAuth } from "./auth-context"
import { getLanguageConfig } from "@/lib/config/index"
import { authenticatedRequest } from "@/lib/api/request"

type Language = "zh" | "en"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string, params?: Record<string, string | number>) => string
}

const translations = {
  zh: {
    // Navigation
    "nav.home": "首页",
    "nav.binClassify": "卡分类",
    "nav.cvvCheck": "CVV检测",
    "nav.binQuery": "BIN查询",
    "nav.infoGenerate": "信息生成",

    "nav.recharge": "充值",
    "nav.login": "登录",
    "nav.register": "注册",

    // Home page
    "home.newBadge": "专业银行卡检测平台",
    "home.title": "cc-m7 银行卡检测",
    "home.titleHighlight": "专业可靠",
    "home.subtitle":
      "提供全面的银行卡有效性检测服务，包括卡分类、CVV验证、BIN查询等专业功能。安全、快速、准确的金融科技解决方案。",
    "home.startDetection": "开始检测",
    "home.learnMore": "了解更多",
    "home.cardValid": "有效",
    "home.detectionTime": "检测时间: 0.2秒",
    "home.stats.accuracy": "检测准确率",
    "home.stats.dailyChecks": "日检测量",
    "home.stats.responseTime": "平均响应时间",
    "home.stats.service": "全天候服务",
    "home.stats.accuracyValue": "99.9%",
    "home.stats.dailyChecksValue": "50万+",
    "home.stats.responseTimeValue": "0.1秒",
    "home.stats.serviceValue": "24/7",
    "home.coreFeatures": "核心功能",
    "home.featuresSubtitle": "专业的银行卡检测服务，满足您的各种需求",
    "home.binClassify": "卡分类",
    "home.binClassifyDesc": "精确识别银行卡BIN码，提供详细的发卡行、卡片类型、国家等信息分类。",
    "home.cvvCheck": "CVV批量检测",
    "home.cvvCheckDesc": "专业的CVV批量检测工具，支持多种检测模式和通道选择",
    "home.binQuery": "BIN查询",
    "home.binQueryDesc": "快速查询银行卡BIN码信息，获取详细的卡片和银行数据。",
    "home.learnMoreLink": "了解更多",
    "home.whyChoose": "为什么选择我们",
    "home.fastDetection": "极速检测",
    "home.fastDetectionDesc": "毫秒级响应，批量处理能力强",
    "home.highAccuracy": "高准确率",
    "home.highAccuracyDesc": "99.9%的检测准确率，数据可靠",
    "home.globalCoverage": "全球覆盖",
    "home.globalCoverageDesc": "支持全球主要银行卡类型",
    "home.testimonial": "专业可靠的银行卡检测服务，帮助我们大大提升了业务效率和数据准确性。",
    "home.testimonialAuthor": "— 金融科技公司 CTO",
    "home.ctaTitle": "开始使用专业银行卡检测服务",
    "home.ctaSubtitle": "立即体验我们的银行卡检测平台，提升您的业务效率",
    "home.freeTrial": "免费试用",
    "home.contactSupport": "联系客服",
    "home.footer.brandTitle": "专业银行卡服务",
    "home.footer.brandDesc": "提供全方位的银行卡检测和分析服务，包括卡分类、CVV验证、实时查询等专业功能。",
    "home.footer.coreServices": "核心服务",
    "home.footer.binClassify": "BIN智能分类",
    "home.footer.cvvVerification": "CVV实时验证",
    "home.footer.batchProcessing": "批量数据处理",
    "home.footer.statusMonitoring": "实时状态监控",
    "home.footer.advantages": "服务优势",
    "home.footer.highAccuracy": "高准确率",
    "home.footer.fastResponse": "快速响应",
    "home.footer.secureReliable": "安全可靠",
    "home.footer.service247": "24/7服务",
    "home.footer.globalSupport": "全球支持",
    "home.footer.advantagesDesc": "覆盖全球主要银行和卡组织，支持多种检测模式",
    "home.footer.copyright": "© 2025 专业银行卡检测平台. 保留所有权利.",
    "home.footer.serviceStatus": "服务状态: 正常运行",
    "home.footer.dataUpdate": "数据更新: 实时同步",
    "home.footer.online": "在线",

    // Customer Service
    "customerService.bubbleMessage1": "有问题请跟我对话！",
    "customerService.bubbleMessage2": "需要帮助吗？我在这里！",
    "customerService.bubbleMessage3": "遇到困难？点击我聊聊！",
    "customerService.bubbleMessage4": "我可以帮您解决问题！",
    "customerService.bubbleMessage5": "有疑问随时找我哦～",
    "customerService.hoverTooltip": "点击和我聊天！",

    // Maintenance
    "maintenance.title": "网站维护中",
    "maintenance.message": "系统正在维护中，请稍后再试",
    "maintenance.endTime": "预计结束时间",
    "maintenance.completed": "维护已结束",
    "maintenance.close": "我知道了",

    // Login page
    "login.welcome": "欢迎回来",
    "login.subtitle": "登录您的账户以继续使用",
    "login.email": "邮箱地址",
    "login.emailPlaceholder": "输入您的邮箱",
    "login.password": "密码",
    "login.passwordPlaceholder": "输入您的密码",
    "login.forgotPassword": "忘记密码？",
    "login.loginButton": "登录",
    "login.loggingIn": "登录中...",
    "login.loginSuccess": "登录成功！正在跳转到首页...",
    "login.loginFailed": "登录失败，请检查账号密码",
    "login.loginError": "登录过程中发生错误",
    "login.or": "或者",
    "login.noAccount": "还没有账户？",
    "login.register": "立即注册",
    "login.wechat": "微信",

    // User dropdown
    "user.accountInfo": "账户信息",
    "user.logout": "退出登录",

    // CVV Check page
    "cvv.title": "卡批量检测",
    "cvv.subtitle": "专业的卡批量检测工具，支持多种检测模式和通道选择",
    "cvv.inputLabel": "输入银行卡信息",
    "cvv.inputPlaceholder": "请输入银行卡号，每行一条\n格式1：卡号|月|年|cvv\n格式2：卡号|月|年|cvv|其他",
    "cvv.detectButton": "开始检测",
    "cvv.costHint": "将消耗 {count} 个M币",
    "cvv.insufficientBalance": "余额不足，请先充值",
    "cvv.results": "检测结果",
    "cvv.cardNumber": "卡号",
    "cvv.cvvCode": "CVV码",
    "cvv.status": "状态",
    "cvv.valid": "有效",
    "cvv.invalid": "无效",
    "cvv.unknown": "未知",
    "cvv.validCount": "有效",
    "cvv.invalidCount": "无效",
    "cvv.invalidLabel": "无效",
    "cvv.copy": "复制",
    "cvv.export": "导出CSV",
    "cvv.noResults": "暂无检测结果",
    "cvv.detectionConfig": "检测配置",
    "cvv.selectModeAndChannel": "选择检测模式和通道",
    "cvv.detectionMode": "检测模式",
    "cvv.selectChannel": "选择通道",
    "cvv.currentSelection": "当前选择",
    "cvv.consumption": "消耗",
    "cvv.consumptionLabel": "消耗",
    "cvv.speedLabel": "速度",
    "cvv.mCoins": "m币",
    "cvv.speed": "速度",
    "cvv.description": "说明",
    "cvv.nextStepInput": "下一步：输入卡号",
    "cvv.inputTitle": "CVV输入",
    "cvv.currentConfig": "当前配置",
    "cvv.mode": "模式",
    "cvv.cvvList": "CVV列表",
    "cvv.previousStep": "上一步",
    "cvv.startPrecheck": "开始预检测",
    "cvv.prechecking": "预检测中",
    "cvv.formalChecking": "正式检测中",
    "cvv.startFormalCheck": "开始正式检测",
    "cvv.precheckResultsTitle": "预检测结果",
    "cvv.formatVerificationComplete": "格式验证完成",
    "cvv.budget": "预算",
    "cvv.estimatedConsumption": "预计消耗",
    "cvv.autoStopOptional": "自动停止（可选）",
    "cvv.autoStopPlaceholder": "输入有效数量",
    "cvv.autoStopDescription": "当检测到指定数量的有效卡时自动停止检测。注意：由于本系统基于多通道检测，实际检测的有效数量可能会大于输入的有效停止数量，大约在10的误差范围内。",
    "cvv.precheckSuccess": "预检测成功",
    "cvv.noValidCVVs": "没有有效的CVV",
    "cvv.precheckFailed": "预检测失败",
    "cvv.allCVVsFormatCorrect": "所有CVV格式都正确",
    "cvv.returnToModify": "返回修改",
    "cvv.maxValid": "最大有效数",
    "cvv.copiedValidCards": "已复制 {count} 条有效卡片",
    "cvv.copiedInvalidCards": "已复制 {count} 条无效卡片",
    "cvv.copyFailed": "复制失败，请重试",
    "cvv.insufficientBalanceTitle": "余额不足",
    "cvv.cannotStartDetection": "无法启动检测",
    "cvv.pleaseRechargeFirst": "请先充值后再进行检测。",
    "cvv.goToRecharge": "去充值",
    "cvv.detectionStartFailed": "检测启动失败",
    "cvv.cannotStartDetectionTask": "无法启动检测任务",
    "cvv.confirm": "确认",
    "cvv.cancel": "取消",
    "cvv.copyAllValidCards": "批量复制有效卡片",
    "cvv.copyAllInvalidCards": "批量复制无效卡片",
    "cvv.cardValidating": "银行卡验证中",
    "cvv.formatError": "格式错误",
    "cvv.viewProgress": "查看进度",
    "cvv.viewResults": "查看结果",
    "cvv.back": "返回",
    "cvv.retry": "重试",
    "cvv.required": "需要",
    "cvv.current": "当前",
    "cvv.shortage": "缺少",
    "cvv.thisDetectionTask": "本次检测任务",
    "cvv.actualDetected": "实际检测条数",
    "cvv.totalCVVCount": "总CVV数量",
    "cvv.totalConsumedMCoins": "共消耗M币",
    "cvv.viewDetectionResults": "查看检测结果",
    "cvv.success": "成功",
    "cvv.retryWithCountdown": "重试 ({count}s)",
    "cvv.detectionCompleted": "检测完成",
    "cvv.detectionInProgress": "检测进行中",
    "cvv.statusAlert": "状态提示",
    "cvv.insufficientMCoins": "M币不足",
    "cvv.serviceUnavailable": "服务不可用",
    "cvv.serverError": "服务器错误",
    "cvv.detectionFailed": "检测失败",
    "cvv.systemStatusAbnormal": "系统状态异常",
    "cvv.detectionStopped": "检测已停止",
    "cvv.stopDetectionFailed": "停止检测失败",
    "cvv.completed": "已完成",
    "cvv.records": "条",
    "cvv.networkError": "网络错误，请稍后重试",
    "cvv.insufficientBalanceRetry": "余额不足，请充值后重试",
    "cvv.detectionStartFailedRetry": "检测启动失败，请稍后重试",
    "cvv.insufficientBalance": "余额不足",
    "cvv.loadingProgress": "正在获取检测进度...",
    "cvv.loadingProgressDesc": "请稍候，正在加载检测数据",
    "cvv.loadingResults": "正在获取检测结果...",
    "cvv.loadingResultsDesc": "请稍候，正在加载检测结果数据",
    "cvv.loadingConfig": "正在加载检测配置...",
    "cvv.loadingConfigDesc": "请稍候，正在加载可用的检测模式和通道信息",
    "cvv.configLoadFailed": "配置加载失败",
    "cvv.reload": "重新加载",
    "cvv.maintenance": "维护中",
    "cvv.stopRequestFailed": "停止检测请求失败",
    "cvv.systemStatus": "系统状态",
    "cvv.detectionService": "检测服务",
    "cvv.channelStatus": "通道状态",
    "cvv.detectionProgress": "检测进度",
    "cvv.channelUsers": "使用此通道的用户",
    "cvv.people": "人",
    "cvv.channelInfo": "通道信息",
    "cvv.channelIdLabel": "通道ID",
    "cvv.channel": "通道",
    "cvv.waitingForCancel": "正在等待停止完成...",
    "cvv.stopping": "停止中...",
    "cvv.usingMode": "使用模式",
    "cvv.stopDetection": "停止检测",
    "cvv.detectingCVVs": "正在检测的CVV",
    "cvv.noCVVsCurrentlyDetecting": "当前没有正在检测的CVV",
    "cvv.moreCVVsDetecting": "还有更多CVV正在检测中",
    "cvv.progress": "进度",
    "cvv.consumedMCoin": "已消耗M币",
    "cvv.autoStopSet": "已设置自动停止",
    "cvv.selectChannelFirst": "请先选择检测通道",
    "cvv.detectionPassed": "检测通过",
    "cvv.detectionFailed": "检测失败",
    "cvv.cannotDetermine": "无法确定",
    "cvv.noDataForStatus": "暂无{status}数据",
    "cvv.copyAll": "复制全部",
    "cvv.items": "条",
    "cvv.detectionResults": "检测结果",
    "cvv.totalConsumption": "总消耗",
    "cvv.taskId": "任务ID",
    "cvv.copyTaskId": "复制任务ID",
    "cvv.mCoinsUnit": "M币",
    "cvv.detectionStatistics": "检测统计",
    "cvv.completionTime": "检测完成时间",
    "cvv.newDetection": "新的检测",
    "cvv.resetting": "重置中...",
    "cvv.validTab": "有效",
    "cvv.invalidTab": "无效",
    "cvv.unknownTab": "未知",
    "cvv.validStatus": "有效",
    "cvv.invalidStatus": "无效",
    "cvv.unknownStatus": "未知",
    "cvv.retest": "重新检测",
    "cvv.stepConfig": "配置选择",
    "cvv.stepInput": "CVV输入",
    "cvv.stepPrecheck": "预检测",
    "cvv.stepDetecting": "检测中",
    "cvv.stepResults": "检测结果",
    "cvv.statusOnline": "在线",
    "cvv.statusBusy": "繁忙",
    "cvv.statusCrowded": "拥挤",
    "cvv.statusOffline": "离线",
    "cvv.detectionCompleted": "检测完成",
    "cvv.detectionCompletedDesc": "您的CVV检测已完成，点击下方按钮查看检测结果",
    "cvv.viewResults": "查看检测结果",
    "cvv.detectionInProgress": "检测进行中",
    "cvv.detectionInProgressDesc": "您的CVV检测正在进行中，点击下方按钮查看实时进度",
    "cvv.viewProgress": "查看检测进度",
    "cvv.loadingProgress": "正在加载进度数据...",
    "cvv.loadingResults": "正在加载结果数据...",
    "cvv.channel1": "通道1",
    "cvv.channel2": "通道2",
    "cvv.channel3": "通道3",
    "cvv.channel4": "通道4",
    "cvv.channel5": "通道5",
    "cvv.speedFast": "快速",
    "cvv.speedMedium": "中等",
    "cvv.speedSlow": "较慢",
    "cvv.speedVeryFast": "极快",
    "cvv.channel1Desc": "高成功率通道，适合大批量检测",
    "cvv.channel2Desc": "稳定通道，平衡速度与准确性",
    "cvv.channel3Desc": "低消耗通道，适合精准检测",
    "cvv.channel4Desc": "高速通道，适合紧急检测",
    "cvv.channel5Desc": "备用通道，稳定可靠",
    "cvv.footer.title": "CVV智能检测",
    "cvv.footer.description": "专业的CVV验证系统，采用多通道检测技术，提供高效、准确的信用卡验证服务，支持实时检测和批量处理。",
    "cvv.footer.coreFeatures": "核心特性",
    "cvv.footer.multiChannelDetection": "多通道智能检测",
    "cvv.footer.realTimeFeedback": "实时验证反馈",
    "cvv.footer.batchProcessing": "批量数据处理",
    "cvv.footer.autoStopControl": "自动停止控制",
    "cvv.footer.security": "安全保障",
    "cvv.footer.sslEncryption": "SSL加密",
    "cvv.footer.dataProtection": "数据保护",
    "cvv.footer.privacySecurity": "隐私安全",
    "cvv.footer.realTimeMonitoring": "实时监控",
    "cvv.footer.riskControl": "风险控制",
    "cvv.footer.complianceDetection": "合规检测",
    "cvv.footer.securityStandard": "采用银行级安全标准，确保检测过程安全可靠",
    "cvv.footer.copyright": "© 2025 CVV智能检测系统. 保留所有权利.",
    "cvv.footer.detectionSpeed": "检测速度: 毫秒级响应",
    "cvv.footer.accuracy": "准确率: 99.9%+",
    "cvv.footer.securityCertification": "安全认证",

    // BIN Classify page
    "bin.title": "卡分类",
    "bin.systemTitle": "智能卡片分类系统",
    "bin.systemSubtitle": "基于BIN码的高效银行卡分类工具，支持多维度智能分析",
    "bin.subtitle": "银行卡BIN码分类和信息查询",
    "bin.inputLabel": "输入银行卡号",
    "bin.cardInputTitle": "卡号数据输入",
    "bin.inputPlaceholder": "请输入卡号信息，每行一个：\n\n支持格式：\n1. 仅卡号：4111111111111111\n2. 卡号+日期：4111111111111111|12|25\n3. 卡号+日期+CVV：4111111111111111|12|25|123\n4. 完整信息：4111111111111111|12|25|123|......\n\n支持主流卡组织：Visa、Mastercard、Amex、Discover、JCB、UnionPay等",
    "bin.inputRecords": "已输入 {count} 条记录",
    "bin.batchProcessing": "支持批量处理",
    "bin.queryButton": "查询卡片信息",
    "bin.querying": "查询中...",
    "bin.dataSourceTitle": "数据源信息",
    "bin.dataSource": "数据来源",
    "bin.dataSourceDesc": "来自国际卡组织（Visa、Mastercard、UnionPay、Amex 等）及各大发卡行内部数据，结合多方支付网络与银行验证数据。",
    "bin.dataAccuracy": "数据准确性",
    "bin.dataAccuracyDesc": "通过多重校验机制与用户反馈系统，确保 BIN 信息识别准确率高达",
    "bin.dataUpdate": "数据更新",
    "bin.dataUpdateDesc": "每日自动同步更新，保证信息实时、权威。",
    "bin.realTimeUpdate": "实时更新",
    "bin.filterLabel": "筛选条件",
    "bin.filterAll": "全部",
    "bin.filterCredit": "信用卡",
    "bin.filterDebit": "借记卡",
    "bin.filterPrepaid": "预付卡",
    "bin.classifyButton": "开始分类",
    "bin.results": "分类结果",
    "bin.cardType": "卡片类型",
    "bin.bank": "发卡银行",
    "bin.country": "国家",
    "bin.brand": "卡片品牌",
    "bin.level": "卡片等级",
    "bin.cardCopied": "卡号已复制到剪贴板",
    "bin.copyFailed": "复制失败，请手动复制",
    "bin.cardsCopied": "已复制 {count} 张卡号到剪贴板",
    "bin.filtering": "筛选数据中...",
    "bin.categoryLabels.brand": "卡片品牌",
    "bin.categoryLabels.type": "卡片种类",
    "bin.categoryLabels.level": "卡片等级",
    "bin.categoryLabels.bank": "发卡行",
    "bin.categoryLabels.country": "发卡国家",
    "bin.categoryLabels.product": "产品名称",
    "bin.footer.brandTitle": "智能卡片分析",
    "bin.footer.brandDesc": "基于BIN码的高效银行卡分类工具，支持多维度智能分析，为您提供准确可靠的卡片信息识别服务。",
    "bin.footer.coreFeatures": "核心特性",
    "bin.footer.multiDimensionClassification": "多维度智能分类",
    "bin.footer.realTimeBINQuery": "实时BIN信息查询",
    "bin.footer.batchDataProcessing": "批量数据处理",
    "bin.footer.accuracyRate": "99.9%识别准确率",
    "bin.footer.globalSupport": "全球支持",
    "bin.footer.globalSupportDesc": "支持全球主流卡组织，覆盖200+国家和地区",
    "bin.footer.copyright": "© 2025 智能卡片分析系统. 保留所有权利.",
    "bin.footer.dataUpdate": "数据更新: 实时同步",
    "bin.footer.serviceStatus": "服务状态: 正常运行",
    "bin.footer.online": "在线",
    "bin.filter.title": "多维度筛选",
    "bin.filter.newQuery": "新查询",
    "bin.filter.statistics": "统计",
    "bin.filter.query": "查询:",
    "bin.filter.filtered": "筛选:",
    "bin.filter.total": "总数:",
    "bin.filter.classification": "分类:",
    "bin.filter.mainCategory": "主分类维度",
    "bin.filter.addFilter": "添加筛选条件",
    "bin.filter.currentFilters": "当前筛选条件:",
    "bin.filter.select": "选择...",
    "bin.filter.all": "全部",
    "bin.filter.addFilterHint": "添加筛选条件来过滤卡片结果",
    "bin.results.classifiedBy": "按 {category} 分类结果",
    "bin.results.groups": "{count} 个分组",
    "bin.results.filtering": "筛选中...",
    "bin.results.selected": "已选择: {name} ({count}张卡)",

    // BIN Classify Feature Page
    "binFeature.hero.title": "卡分类",
    "binFeature.hero.subtitle": "精确识别银行卡BIN码，提供详细的发卡行、卡片类型、国家等信息分类",
    "binFeature.features.title": "核心功能",
    "binFeature.features.subtitle": "强大的银行卡分类功能，满足您的各种需求",
    "binFeature.features.accuracy.title": "精确识别",
    "binFeature.features.accuracy.desc": "基于国际卡组织官方数据，准确识别BIN码，提供发卡行、卡片类型、国家等详细信息",
    "binFeature.features.details.title": "详细信息",
    "binFeature.features.details.desc": "提供卡片品牌、类型、等级、发卡行、发卡国家、产品名称等多维度分类信息",
    "binFeature.features.batch.title": "批量处理",
    "binFeature.features.batch.desc": "支持批量输入和处理，快速分类大量卡片数据，提高工作效率",
    "binFeature.features.realtime.title": "实时结果",
    "binFeature.features.realtime.desc": "实时返回分类结果，支持多维度筛选和导出，方便数据管理",
    "binFeature.useCases.title": "使用场景",
    "binFeature.useCases.subtitle": "适用于各种业务场景",
    "binFeature.useCases.management.title": "卡片管理",
    "binFeature.useCases.management.desc": "帮助金融机构和支付平台快速识别和管理大量卡片数据",
    "binFeature.useCases.analysis.title": "数据分析",
    "binFeature.useCases.analysis.desc": "通过卡片分类信息进行数据分析和报表生成，支持业务决策",
    "binFeature.useCases.risk.title": "风险控制",
    "binFeature.useCases.risk.desc": "基于卡片类型和国家信息进行风险识别和控制，提升安全性",
    "binFeature.advantages.title": "技术优势",
    "binFeature.advantages.subtitle": "专业可靠的技术保障",
    "binFeature.advantages.accuracy.title": "高准确率",
    "binFeature.advantages.accuracy.desc": "99.9%的识别准确率，数据来源权威可靠",
    "binFeature.advantages.speed.title": "快速响应",
    "binFeature.advantages.speed.desc": "毫秒级响应速度，批量处理能力强",
    "binFeature.advantages.coverage.title": "全球覆盖",
    "binFeature.advantages.coverage.desc": "支持全球主要卡组织，覆盖200+国家和地区",
    "binFeature.cta.title": "立即开始使用",
    "binFeature.cta.subtitle": "体验专业的卡分类服务，提升您的工作效率",
    "binFeature.cta.startButton": "立即使用",
    "binFeature.cta.backButton": "返回首页",

    // CVV Check Feature Page
    "cvvFeature.hero.title": "CVV批量检测",
    "cvvFeature.hero.subtitle": "专业的CVV批量检测工具，支持多种检测模式和通道选择",
    "cvvFeature.features.title": "核心功能",
    "cvvFeature.features.subtitle": "强大的CVV检测功能，满足您的各种需求",
    "cvvFeature.features.batch.title": "批量检测",
    "cvvFeature.features.batch.desc": "支持批量输入和处理，快速检测大量CVV数据，提高工作效率",
    "cvvFeature.features.modes.title": "多种模式",
    "cvvFeature.features.modes.desc": "支持测试模式、快速检测、备用检测等多种检测模式，满足不同场景需求",
    "cvvFeature.features.channels.title": "通道选择",
    "cvvFeature.features.channels.desc": "提供多个检测通道，支持不同速度和准确率的选择，灵活配置检测策略",
    "cvvFeature.features.realtime.title": "实时反馈",
    "cvvFeature.features.realtime.desc": "实时显示检测进度和结果，支持自动停止控制，方便监控和管理",
    "cvvFeature.useCases.title": "使用场景",
    "cvvFeature.useCases.subtitle": "适用于各种业务场景",
    "cvvFeature.useCases.verification.title": "卡片验证",
    "cvvFeature.useCases.verification.desc": "帮助金融机构和支付平台快速验证大量卡片的有效性",
    "cvvFeature.useCases.risk.title": "风险控制",
    "cvvFeature.useCases.risk.desc": "通过批量检测识别无效卡片，有效降低业务风险和损失",
    "cvvFeature.useCases.management.title": "数据管理",
    "cvvFeature.useCases.management.desc": "批量检测和管理卡片数据，支持结果导出和提取码生成",
    "cvvFeature.advantages.title": "技术优势",
    "cvvFeature.advantages.subtitle": "专业可靠的技术保障",
    "cvvFeature.advantages.accuracy.title": "高准确率",
    "cvvFeature.advantages.accuracy.desc": "99.9%+的检测准确率，数据来源权威可靠",
    "cvvFeature.advantages.speed.title": "快速响应",
    "cvvFeature.advantages.speed.desc": "毫秒级响应速度，支持高并发批量处理",
    "cvvFeature.advantages.security.title": "安全可靠",
    "cvvFeature.advantages.security.desc": "采用银行级安全标准，SSL加密传输，确保数据安全",
    "cvvFeature.cta.title": "立即开始使用",
    "cvvFeature.cta.subtitle": "体验专业的CVV检测服务，提升您的工作效率",
    "cvvFeature.cta.startButton": "立即使用",
    "cvvFeature.cta.backButton": "返回首页",

    // BIN Query Feature Page
    "binQueryFeature.hero.title": "BIN查询",
    "binQueryFeature.hero.subtitle": "快速查询银行卡BIN码信息，获取详细的卡片和银行数据",
    "binQueryFeature.features.title": "核心功能",
    "binQueryFeature.features.subtitle": "强大的BIN查询功能，满足您的各种需求",
    "binQueryFeature.features.fast.title": "快速查询",
    "binQueryFeature.features.fast.desc": "实时查询BIN码信息，毫秒级响应速度，快速获取卡片和银行数据",
    "binQueryFeature.features.details.title": "详细信息",
    "binQueryFeature.features.details.desc": "提供卡片品牌、类型、等级、发卡行、发卡国家、产品名称等详细信息",
    "binQueryFeature.features.bank.title": "银行数据",
    "binQueryFeature.features.bank.desc": "包含银行名称、官网、联系电话等完整的银行信息，方便业务对接",
    "binQueryFeature.features.accuracy.title": "准确可靠",
    "binQueryFeature.features.accuracy.desc": "基于国际卡组织官方数据，准确识别BIN码，提供权威可靠的信息",
    "binQueryFeature.useCases.title": "使用场景",
    "binQueryFeature.useCases.subtitle": "适用于各种业务场景",
    "binQueryFeature.useCases.verification.title": "卡片验证",
    "binQueryFeature.useCases.verification.desc": "帮助支付平台和金融机构快速验证卡片信息，识别卡片类型和发卡行",
    "binQueryFeature.useCases.analysis.title": "数据分析",
    "binQueryFeature.useCases.analysis.desc": "通过BIN码查询进行数据分析和报表生成，支持业务决策和市场研究",
    "binQueryFeature.useCases.integration.title": "系统集成",
    "binQueryFeature.useCases.integration.desc": "提供API接口，方便集成到现有系统中，支持批量查询和自动化处理",
    "binQueryFeature.advantages.title": "技术优势",
    "binQueryFeature.advantages.subtitle": "专业可靠的技术保障",
    "binQueryFeature.advantages.speed.title": "快速响应",
    "binQueryFeature.advantages.speed.desc": "毫秒级响应速度，实时返回查询结果，提升用户体验",
    "binQueryFeature.advantages.accuracy.title": "高准确率",
    "binQueryFeature.advantages.accuracy.desc": "99.9%+的查询准确率，数据来源权威可靠，持续更新",
    "binQueryFeature.advantages.coverage.title": "全球覆盖",
    "binQueryFeature.advantages.coverage.desc": "支持全球主要卡组织和银行，覆盖200+国家和地区",
    "binQueryFeature.cta.title": "立即开始使用",
    "binQueryFeature.cta.subtitle": "体验专业的BIN查询服务，提升您的工作效率",
    "binQueryFeature.cta.startButton": "立即使用",
    "binQueryFeature.cta.backButton": "返回首页",
    "bin.results.clearSelection": "清除选择",
    "bin.results.exportData": "导出数据",
    "bin.results.cards": "张卡",
    "bin.results.clickToView": "点击查看 {count} 张卡片的详细信息",
    "bin.results.moreCards": "还有 {count} 张卡片...",
    "bin.results.contains": "包含 {count} 张卡片",
    "bin.results.copyAllCards": "复制所有卡号",
    "bin.results.cardList": "卡片列表",
    "bin.results.noDetails": "暂无详细信息",
    "bin.results.cardsCount": "{count} 张卡片",

    // Card Extract page
    "extract.title": "卡信息提取",
    "extract.subtitle": "通过提取码获取银行卡信息",
    "extract.codeLabel": "提取码",
    "extract.codePlaceholder": "请输入提取码",
    "extract.verifyCodeLabel": "数据验证码",
    "extract.verifyCodePlaceholder": "请输入验证码",
    "extract.extractButton": "提取信息",
    "extract.remainingAttempts": "今日剩余尝试次数：{count}",
    "extract.noAttempts": "今日尝试次数已用完",
    "extract.success": "提取成功！",
    "extract.failed": "提取失败，请检查提取码或验证码",
    "extract.cardInfo": "卡片信息",
    "extract.cardCount": "卡片数量",
    "extract.detectionTime": "检测时间",
    "extract.dataSource": "数据来源",

    // BIN Query page
    "binQuery.title": "BIN查询系统",
    "binQuery.description": "输入银行卡BIN码查询详细的卡片信息",
    "binQuery.queryTab": "BIN查询",

    "binQuery.refreshing": "刷新中...",
    "binQuery.refresh": "刷新",
    "binQuery.pageInfo": "第",
    "binQuery.totalRecords": "条记录",
    "binQuery.previousPage": "上一页",
    "binQuery.nextPage": "下一页",
    "binQuery.binLabel": "BIN码",
    "binQuery.binInputLabel": "输入BIN码",
    "binQuery.binPlaceholder": "请输入6-8位BIN码，例如：412345",
    "binQuery.queryButton": "查询",
    "binQuery.querying": "查询中",
    "binQuery.tip1": "• BIN码是银行识别码，通常是卡号前6-8位数字",
    "binQuery.tip2": "• 可以查询卡片类型、品牌、发卡行等详细信息",
    "binQuery.tip3": "• 支持Visa、MasterCard、American Express等主流卡片",
    "binQuery.success": "查询成功！",
    "binQuery.failed": "查询失败，请检查BIN码",
    "binQuery.cardType": "卡片类型",
    "binQuery.cardBrand": "卡片品牌",
    "binQuery.cardLevel": "卡片等级",
    "binQuery.bankName": "发卡银行",
    "binQuery.country": "发卡国家",
    "binQuery.currency": "货币",
    "binQuery.website": "银行官网",
    "binQuery.phone": "银行电话",
    "binQuery.results": "查询结果",
    "binQuery.queryTime": "查询时间",
    "binQuery.status.success": "成功",
    "binQuery.status.failed": "失败",
    "binQuery.status.notFound": "未找到",
    "binQuery.footer.title": "BIN码查询",
    "binQuery.footer.description": "专业的银行识别码查询工具，提供准确的卡片基础信息和详细属性，支持实时查询和批量处理。",
    "binQuery.footer.queryCapabilities": "查询能力",
    "binQuery.footer.cardBrandRecognition": "卡片品牌识别",
    "binQuery.footer.issuerInfo": "发卡行信息",
    "binQuery.footer.cardTypeDetection": "卡片类型判断",
    "binQuery.footer.countryRecognition": "国家地区识别",
    "binQuery.footer.technicalSupport": "技术保障",
    "binQuery.footer.querySpeed": "查询速度",
    "binQuery.footer.dataAccuracy": "数据准确率",
    "binQuery.footer.binRange": "支持BIN范围",
    "binQuery.footer.copyright": "© 2025 BIN查询系统. 专业银行识别码查询服务.",
    "binQuery.footer.responseTime": "响应时间: 实时",
    "binQuery.footer.database": "数据库: 最新",
    "binQuery.footer.serviceNormal": "服务正常",

    // Info Generate page
    "info.title": "信息生成",
    "info.systemTitle": "智能信息生成系统",
    "info.subtitle": "根据银行卡号生成完整的身份信息，使用真实地理位置数据",
    "info.inputCardTitle": "卡号输入",
    "info.inputLabel": "输入卡号（每行一个）",
    "info.inputPlaceholder": "请输入卡号，每行一个\n例如：\n4147202688856879\n4207670137072792",
    "info.generateButton": "开始生成",
    "info.generating": "生成中...",
    "info.costPreview": "消耗预览",
    "info.detectedCards": "检测到 {count} 个卡号，需要消耗 {cost} M币",
    "info.costHint": "将消耗 {count} 个M币",
    "info.costPerCard": "每生成一条信息消耗 {price} M币",
    "info.usingRealData": "使用真实地理位置数据生成",
    "info.supportBatch": "支持批量生成，每行一个卡号",
    "info.results": "生成结果",
    "info.resultsCount": "生成结果 ({count}条)",
    "info.exportCSV": "导出CSV",
    "info.noData": "暂无生成数据",
    "info.noDataHint": "输入卡号并点击生成按钮开始",
    "info.name": "姓名",
    "info.country": "国家",
    "info.province": "省/州",
    "info.city": "城市",
    "info.street": "街道",
    "info.zipCode": "邮编",
    "info.phone": "电话",
    "info.email": "邮箱",
    "info.address": "地址",
    "info.expiry": "有效期",
    "info.cardNumber": "卡号",
    "info.generateComplete": "生成完成",
    "info.resultStats": "信息生成结果统计",
    "info.successCount": "成功生成",
    "info.failedCount": "生成失败",
    "info.actualCost": "实际消耗",
    "info.failedCards": "生成失败的卡号",
    "info.failedCardsTitle": "生成失败的卡号",
    "info.copyAll": "复制全部",
    "info.close": "关闭",
    "info.viewResults": "查看结果",
    "info.copied": "信息已复制到剪贴板",
    "info.copyFailed": "复制失败",
    "info.failedCardsCopied": "失败卡号已复制到剪贴板",
    "info.loginRequired": "请先登录",
    "info.enterCardNumber": "请输入卡号",
    "info.enterValidCard": "请输入有效的卡号",
    "info.generateFailed": "生成失败",
    "info.generateError": "生成失败，请稍后重试",
    "info.footer.brandTitle": "智能信息生成",
    "info.footer.brandDesc": "基于真实的个人信息和真实的地理位置数据的智能身份信息生成工具，为您提供完整、准确的个人信息数据。",
    "info.footer.coreFeatures": "核心特性",
    "info.footer.realPersonalInfo": "真实的个人信息",
    "info.footer.realLocation": "真实的地理位置",
    "info.footer.completeIdentity": "完整身份信息生成",
    "info.footer.batchProcessing": "批量数据处理",
    "info.footer.csvExport": "CSV格式导出",
    "info.footer.supportedRegions": "支持地区",
    "info.footer.country.usa": "美国",
    "info.footer.country.uk": "英国",
    "info.footer.country.canada": "加拿大",
    "info.footer.country.australia": "澳洲",
    "info.footer.country.germany": "德国",
    "info.footer.country.france": "法国",
    "info.footer.regionsDesc": "支持200+国家和地区，提供真实的个人信息和地理位置数据",
    "info.footer.copyright": "© 2025 智能信息生成系统. 保留所有权利.",
    "info.footer.dataSource": "数据来源: 真实地理数据库",
    "info.footer.generationSpeed": "生成速度: 毫秒级响应",
    "info.footer.safeReliable": "安全可靠",

    // Recharge page
    "recharge.pageTitle": "充值",
    "recharge.pageSubtitle": "使用USDT购买M币，享受更多功能和优惠折扣",
    "recharge.title": "账户充值",
    "recharge.subtitle": "为您的账户充值M币",
    "recharge.currentBalance": "当前余额",
    "recharge.coins": "M币",
    "recharge.selectAmount": "选择充值金额",
    "recharge.customAmount": "自定义金额",
    "recharge.customPlaceholder": "输入充值金额",
    "recharge.paymentMethod": "支付方式",
    "recharge.usdt": "USDT支付",
    "recharge.packagesTab": "套餐充值",
    "recharge.exchangeCode": "兑换码",
    "recharge.exchangeCodePlaceholder": "请输入您的兑换码",
    "recharge.exchangeCodeRecharge": "兑换码充值",
    "recharge.loadingPackages": "正在加载充值套餐...",
    "recharge.noPackages": "暂无充值套餐",
    "recharge.contactSupport": "请联系客服或稍后重试",
    "recharge.popular": "热门",
    "recharge.selectPackage": "选择套餐",
    "recharge.saveAmount": "节省",
    "recharge.processing": "处理中...",
    "recharge.instructions": "使用说明",
    "recharge.exchangeCodeDesc": "兑换码通常由活动或推广获得，每个兑换码只能使用一次，兑换成功后M币将立即到账。",
    "recharge.paymentDialogTitle": "USDT支付",
    "recharge.paymentDialogDesc": "请使用USDT钱包扫描二维码或转账到指定地址",
    "recharge.purchaseAmount": "购买数量:",
    "recharge.paymentAmount": "支付金额:",
    "recharge.timeLeft": "剩余时间:",
    "recharge.discount": "折扣:",
    "recharge.orderNumber": "订单号:",
    "recharge.generatingQR": "生成二维码中...",
    "recharge.scanQRCode": "使用USDT钱包扫描二维码支付",
    "recharge.walletAddress": "USDT钱包地址 (TRC20)",
    "recharge.addressCopied": "地址已复制到剪贴板",
    "recharge.paymentInstructions": "支付说明:",
    "recharge.cancel": "取消",
    "recharge.paymentCompleted": "我已完成支付",
    "recharge.checkingPayment": "正在获取支付结果",
    "recharge.checkingPaymentDesc": "正在联系支付系统验证您的转账信息...",
    "recharge.verificationTime": "验证时间最多10分钟",
    "recharge.doNotClose": "请不要关闭此窗口，系统正在处理您的支付信息",
    "recharge.confirmCancel": "确认取消支付",
    "recharge.confirmCancelDesc": "您确定要取消当前的支付订单吗？",
    "recharge.cancelNotice": "注意：",
    "recharge.cancelNotice1": "取消后将无法继续使用当前的支付地址",
    "recharge.cancelNotice2": "如果您已经转账，请不要取消",
    "recharge.cancelNotice3": "取消后需要重新选择套餐进行支付",
    "recharge.continuePayment": "继续支付",
    "recharge.cancelling": "取消中...",
    "recharge.confirmCancelBtn": "确认取消",
    "recharge.operationSuccess": "操作成功",
    "recharge.paymentProcessing": "支付处理中",
    "recharge.operationFailed": "操作失败",
    "recharge.addedToAccount": "已添加到您的账户",
    "recharge.processingPayment": "系统正在处理您的支付，请耐心等待",
    "recharge.retryOrContact": "请重试或联系客服",
    "recharge.close": "关闭",
    "recharge.continueRecharge": "继续充值",
    "recharge.retryWait": "点击重试，继续等待",
    "recharge.retry": "重试",
    "recharge.rechargeButton": "立即充值",
    "recharge.useExchangeCode": "使用兑换码",
    "recharge.success": "充值成功！",
    "recharge.failed": "充值失败",
    "recharge.exchangeSuccess": "兑换成功！",
    "recharge.exchangeFailed": "兑换失败，请检查兑换码",
    "recharge.paymentExpired": "支付时间已过期，请重新选择套餐",
    "recharge.successMessage": "充值成功！M币已到账",
    "recharge.failedMessage": "充值失败，请检查支付信息或联系客服",
    "recharge.retryMessage": "充值失败，请稍后重试",
    "recharge.exchangeSuccessMessage": "兑换成功！M币已到账",
    "recharge.paymentPending": "支付还在处理中，请稍候...",
    "recharge.paymentVerifyFailed": "支付验证失败。如果您已经支付，请联系客服处理，或者重新选择套餐进行支付。",
    "recharge.requestTimeout": "请求超时，请点击重试继续检查支付结果",
    "recharge.checkTimeout": "支付结果检查超时，请点击重试",
    "recharge.networkError": "网络错误，请检查网络连接后重试",
    "recharge.pleaseLogin": "请先登录",
    "recharge.footer.serviceTitle": "M币充值服务",
    "recharge.footer.serviceDesc": "安全便捷的USDT充值服务，多种套餐选择，享受专业功能和优惠折扣，支持兑换码快速充值。",
    "recharge.footer.advantages": "充值优势",
    "recharge.footer.packageOptions": "多种套餐选择",
    "recharge.footer.discounts": "优惠折扣活动",
    "recharge.footer.instantCredit": "即时到账服务",
    "recharge.footer.exchangeCode": "兑换码支持",
    "recharge.footer.security": "安全保障",
    "recharge.footer.paymentMethod": "支付方式",
    "recharge.footer.creditTime": "到账时间",
    "recharge.footer.instant": "即时到账",
    "recharge.footer.securityLevel": "安全等级",
    "recharge.footer.bankLevel": "银行级",
    "recharge.footer.copyright": "© 2025 M币充值系统. 安全可靠的数字货币充值服务.",
    "recharge.footer.ssl": "SSL加密",
    "recharge.footer.instantProcessing": "即时处理",
    "recharge.footer.service247": "24/7服务",

    // Account page
    "account.status.completed": "已完成",
    "account.status.pending": "待支付",
    "account.status.processing": "处理中",
    "account.status.timeout": "订单超时",
    "account.status.failed": "失败",
    "account.loginRequired": "请先登录以查看账户信息",
    "account.selectAvatar": "选择头像",
    "account.selectAvatarDesc": "从下面选择一个你喜欢的头像风格和变体",
    "account.currentSelection": "当前选择",
    "account.realTimePreview": "实时预览",
    "account.cancel": "取消",
    "account.saveAvatar": "保存头像",
    "account.saving": "保存中...",
    "account.editProfile": "编辑资料",
    "account.activeUser": "活跃用户",
    "account.profile": "个人资料",
    "account.rechargeRecords": "充值记录",
    "account.personalInfo": "个人信息",
    "account.manageAccount": "管理您的账户信息和偏好设置",
    "account.username": "用户名",
    "account.email": "邮箱地址",
    "account.changePassword": "修改密码",
    "account.newPasswordPlaceholder": "输入新密码（留空则不修改）",
    "account.oldPassword": "旧密码",
    "account.newPassword": "新密码",
    "account.confirmNewPassword": "确认新密码",
    "account.oldPasswordPlaceholder": "请输入当前密码",
    "account.newPasswordPlaceholder2": "请输入新密码（至少6个字符）",
    "account.confirmPasswordPlaceholder": "请再次输入新密码",
    "account.changePasswordDesc": "修改您的登录密码",
    "account.changingPassword": "修改中...",
    "account.passwordChangeSuccess": "密码修改成功",
    "account.passwordChangeSuccessDesc": "您的密码已成功修改，请使用新密码登录。",
    "account.joinDate": "注册时间",
    "account.accountStatus": "账户状态",
    "account.normal": "正常",
    "account.saveChanges": "保存更改",
    "account.viewRechargeHistory": "查看您的所有充值交易历史",
    "account.dateRange": "日期范围",
    "account.export": "导出",
    "account.date": "日期",
    "account.orderNumber": "订单编号",
    "account.rechargeAmount": "充值金额",
    "account.paymentAmount": "支付金额",
    "account.paymentMethod": "支付方式",
    "account.status": "状态",
    "account.transactionHash": "交易哈希",
    "account.noRechargeRecords": "暂无充值记录",
    "account.saveSuccess": "保存成功",
    "account.profileUpdated": "您的个人资料已成功更新。",
    "account.confirm": "确定",

    // Register page
    "register.title": "创建账户",
    "register.subtitle": "注册新账户开始使用我们的服务",
    "register.username": "用户名",
    "register.usernamePlaceholder": "输入您的用户名",
    "register.email": "邮箱地址",
    "register.emailPlaceholder": "输入您的邮箱",
    "register.password": "密码",
    "register.passwordPlaceholder": "创建安全密码",
    "register.confirmPassword": "确认密码",
    "register.confirmPasswordPlaceholder": "再次输入密码",
    "register.passwordMismatch": "密码不匹配",
    "register.passwordReq8Chars": "至少8个字符",
    "register.passwordReqUppercase": "包含大写字母",
    "register.passwordReqLowercase": "包含小写字母",
    "register.passwordReqNumber": "包含数字",
    "register.agreeTerms": "我同意",
    "register.termsOfService": "服务条款",
    "register.and": "和",
    "register.privacyPolicy": "隐私政策",
    "register.registerButton": "创建账户",
    "register.creating": "创建中...",
    "register.registerSuccess": "注册成功！正在跳转到登录页面...",
    "register.registerFailed": "注册失败，请重试",
    "register.registerError": "注册过程中发生错误",
    "register.backToRegister": "返回注册",
    "register.hasAccount": "已有账户？",
    "register.login": "立即登录",

    // Language selector
    "language.chinese": "中文",
    "language.english": "English",

    // Common
    "common.loading": "加载中...",
    "common.error": "发生错误",
    "common.success": "操作成功",
    "common.cancel": "取消",
    "common.confirm": "确认",
    "common.close": "关闭",
  },
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.binClassify": "Card Classification",
    "nav.cvvCheck": "CVV Check",
    "nav.binQuery": "BIN Query",
    "nav.infoGenerate": "Info Generate",

    "nav.recharge": "Recharge",
    "nav.login": "Login",
    "nav.register": "Register",

    // Home page
    "home.newBadge": "Professional Card Detection Platform",
    "home.title": "cc-m7 Card Detection",
    "home.titleHighlight": "Professional & Reliable",
    "home.subtitle":
      "Comprehensive bank card validity detection services, including BIN classification, CVV verification, card information extraction and other professional functions. Secure, fast, and accurate fintech solutions.",
    "home.startDetection": "Start Detection",
    "home.learnMore": "Learn More",
    "home.cardValid": "Valid",
    "home.detectionTime": "Detection Time: 0.2s",
    "home.stats.accuracy": "Detection Accuracy",
    "home.stats.dailyChecks": "Daily Detections",
    "home.stats.responseTime": "Avg Response Time",
    "home.stats.service": "24/7 Service",
    "home.stats.accuracyValue": "99.9%",
    "home.stats.dailyChecksValue": "500K+",
    "home.stats.responseTimeValue": "0.1s",
    "home.stats.serviceValue": "24/7",
    "home.coreFeatures": "Core Features",
    "home.featuresSubtitle": "Professional bank card detection services to meet all your needs",
    "home.binClassify": "Card Classification",
    "home.binClassifyDesc":
      "Accurately identify bank card BIN codes, providing detailed issuer, card type, country and other information classification.",
    "home.cvvCheck": "CVV Batch Detection",
    "home.cvvCheckDesc": "Professional CVV batch detection tool with multiple detection modes and channel selection",
    "home.binQuery": "BIN Query",
    "home.binQueryDesc":
      "Fast BIN code query service to get detailed card and bank information.",
    "home.learnMoreLink": "Learn More",
    "home.whyChoose": "Why Choose Us",
    "home.fastDetection": "Lightning Fast",
    "home.fastDetectionDesc": "Millisecond response with strong batch processing capability",
    "home.highAccuracy": "High Accuracy",
    "home.highAccuracyDesc": "99.9% detection accuracy with reliable data",
    "home.globalCoverage": "Global Coverage",
    "home.globalCoverageDesc": "Support for major bank card types worldwide",
    "home.testimonial":
      "Professional and reliable bank card detection service that has greatly improved our business efficiency and data accuracy.",
    "home.testimonialAuthor": "— CTO, Fintech Company",
    "home.ctaTitle": "Start Using Professional Card Detection Services",
    "home.ctaSubtitle": "Experience our bank card detection platform now and boost your business efficiency",
    "home.freeTrial": "Free Trial",
    "home.contactSupport": "Contact Support",
    "home.footer.brandTitle": "Professional Bank Card Services",
    "home.footer.brandDesc": "Comprehensive bank card detection and analysis services, including card classification, CVV verification, real-time query and other professional functions.",
    "home.footer.coreServices": "Core Services",
    "home.footer.binClassify": "BIN Intelligent Classification",
    "home.footer.cvvVerification": "CVV Real-time Verification",
    "home.footer.batchProcessing": "Batch Data Processing",
    "home.footer.statusMonitoring": "Real-time Status Monitoring",
    "home.footer.advantages": "Service Advantages",
    "home.footer.highAccuracy": "High Accuracy",
    "home.footer.fastResponse": "Fast Response",
    "home.footer.secureReliable": "Secure & Reliable",
    "home.footer.service247": "24/7 Service",
    "home.footer.globalSupport": "Global Support",
    "home.footer.advantagesDesc": "Covering major banks and card organizations worldwide, supporting multiple detection modes",
    "home.footer.copyright": "© 2025 Professional Bank Card Detection Platform. All rights reserved.",
    "home.footer.serviceStatus": "Service Status: Running normally",
    "home.footer.dataUpdate": "Data Update: Real-time sync",
    "home.footer.online": "Online",

    // Customer Service
    "customerService.bubbleMessage1": "Have questions? Chat with me!",
    "customerService.bubbleMessage2": "Need help? I'm here!",
    "customerService.bubbleMessage3": "Having trouble? Click me to chat!",
    "customerService.bubbleMessage4": "I can help you solve problems!",
    "customerService.bubbleMessage5": "Feel free to ask me anytime~",
    "customerService.hoverTooltip": "Click to chat with me!",

    // Maintenance
    "maintenance.title": "Maintenance",
    "maintenance.message": "The system is under maintenance, please try again later",
    "maintenance.endTime": "Estimated End Time",
    "maintenance.completed": "Maintenance completed",
    "maintenance.close": "I Understand",

    // Login page
    "login.welcome": "Welcome Back",
    "login.subtitle": "Sign in to your account to continue",
    "login.email": "Email Address",
    "login.emailPlaceholder": "Enter your email",
    "login.password": "Password",
    "login.passwordPlaceholder": "Enter your password",
    "login.forgotPassword": "Forgot password?",
    "login.loginButton": "Sign In",
    "login.loggingIn": "Logging in...",
    "login.loginSuccess": "Login successful! Redirecting to homepage...",
    "login.loginFailed": "Login failed, please check your email and password",
    "login.loginError": "An error occurred during login",
    "login.or": "or",
    "login.noAccount": "Don't have an account?",
    "login.register": "Sign up now",
    "login.wechat": "WeChat",

    // User dropdown
    "user.accountInfo": "Account Info",
    "user.logout": "Logout",

    // CVV Check page
    "cvv.title": "CVV Batch Detection",
    "cvv.subtitle": "Professional CVV batch detection tool with multiple detection modes and channel selection",
    "cvv.inputLabel": "Enter Card Information",
    "cvv.inputPlaceholder":
      "Enter card numbers, one per line\nFormat 1: CardNumber|Month|Year|CVV\nFormat 2: CardNumber|Month|Year|CVV|Other",
    "cvv.detectButton": "Start Detection",
    "cvv.costHint": "Will consume {count} M coins",
    "cvv.insufficientBalance": "Insufficient balance, please recharge first",
    "cvv.results": "Detection Results",
    "cvv.cardNumber": "Card Number",
    "cvv.cvvCode": "CVV Code",
    "cvv.status": "Status",
    "cvv.valid": "Valid",
    "cvv.invalid": "Invalid",
    "cvv.unknown": "Unknown",
    "cvv.validCount": "Valid",
    "cvv.invalidCount": "Invalid",
    "cvv.invalidLabel": "Invalid",
    "cvv.copy": "Copy",
    "cvv.export": "Export CSV",
    "cvv.noResults": "No detection results",
    "cvv.detectionConfig": "Detection Configuration",
    "cvv.selectModeAndChannel": "Select detection mode and channel",
    "cvv.detectionMode": "Detection Mode",
    "cvv.selectChannel": "Select Channel",
    "cvv.currentSelection": "Current Selection",
    "cvv.consumption": "Consumption",
    "cvv.consumptionLabel": "Consumption",
    "cvv.speedLabel": "Speed",
    "cvv.mCoins": "M coins",
    "cvv.speed": "Speed",
    "cvv.description": "Description",
    "cvv.nextStepInput": "Next: Input Card Number",
    "cvv.inputTitle": "CVV Input",
    "cvv.currentConfig": "Current Configuration",
    "cvv.mode": "Mode",
    "cvv.cvvList": "CVV List",
    "cvv.previousStep": "Previous Step",
    "cvv.startPrecheck": "Start Precheck",
    "cvv.prechecking": "Prechecking",
    "cvv.formalChecking": "Formal Detection",
    "cvv.startFormalCheck": "Start Formal Detection",
    "cvv.precheckResultsTitle": "Precheck Results",
    "cvv.formatVerificationComplete": "Format verification complete",
    "cvv.budget": "Budget",
    "cvv.estimatedConsumption": "Estimated consumption",
    "cvv.autoStopOptional": "Auto stop (optional)",
    "cvv.autoStopPlaceholder": "Enter valid count",
    "cvv.autoStopDescription": "Automatically stop detection when the specified number of valid CVVs is reached. Note: Due to multi-channel detection, the actual number of valid detections may exceed the input stop count by approximately 10 within the margin of error.",
    "cvv.precheckSuccess": "Precheck Success",
    "cvv.noValidCVVs": "No valid CVVs",
    "cvv.precheckFailed": "Precheck Failed",
    "cvv.allCVVsFormatCorrect": "All CVVs format is correct",
    "cvv.returnToModify": "Return to Modify",
    "cvv.maxValid": "Max Valid",
    "cvv.copiedValidCards": "Copied {count} valid cards",
    "cvv.copiedInvalidCards": "Copied {count} invalid cards",
    "cvv.copyFailed": "Copy failed, please try again",
    "cvv.insufficientBalanceTitle": "Insufficient Balance",
    "cvv.cannotStartDetection": "Cannot start detection",
    "cvv.pleaseRechargeFirst": "Please recharge before starting detection.",
    "cvv.goToRecharge": "Go to Recharge",
    "cvv.detectionStartFailed": "Detection Start Failed",
    "cvv.cannotStartDetectionTask": "Cannot start detection task",
    "cvv.confirm": "Confirm",
    "cvv.cancel": "Cancel",
    "cvv.copyAllValidCards": "Copy All Valid Cards",
    "cvv.copyAllInvalidCards": "Copy All Invalid Cards",
    "cvv.cardValidating": "Validating cards",
    "cvv.formatError": "Format error",
    "cvv.viewProgress": "View Progress",
    "cvv.viewResults": "View Results",
    "cvv.back": "Back",
    "cvv.retry": "Retry",
    "cvv.required": "Required",
    "cvv.current": "Current",
    "cvv.shortage": "Shortage",
    "cvv.thisDetectionTask": "This Detection Task",
    "cvv.actualDetected": "Actual Detected",
    "cvv.totalCVVCount": "Total CVV Count",
    "cvv.totalConsumedMCoins": "Total Consumed M Coins",
    "cvv.viewDetectionResults": "View Detection Results",
    "cvv.success": "Success",
    "cvv.retryWithCountdown": "Retry ({count}s)",
    "cvv.detectionCompleted": "Detection Completed",
    "cvv.detectionInProgress": "Detection In Progress",
    "cvv.statusAlert": "Status Alert",
    "cvv.insufficientMCoins": "Insufficient M-Coins",
    "cvv.serviceUnavailable": "Service Unavailable",
    "cvv.serverError": "Server Error",
    "cvv.detectionFailed": "Detection Failed",
    "cvv.systemStatusAbnormal": "System Status Abnormal",
    "cvv.detectionStopped": "Detection Stopped",
    "cvv.stopDetectionFailed": "Stop Detection Failed",
    "cvv.completed": "Completed",
    "cvv.records": "records",
    "cvv.networkError": "Network error, please try again later",
    "cvv.insufficientBalanceRetry": "Insufficient balance, please recharge and try again",
    "cvv.detectionStartFailedRetry": "Detection start failed, please try again later",
    "cvv.insufficientBalance": "Insufficient Balance",
    "cvv.loadingProgress": "Loading detection progress...",
    "cvv.loadingProgressDesc": "Please wait, loading detection data",
    "cvv.loadingResults": "Loading detection results...",
    "cvv.loadingResultsDesc": "Please wait, loading detection results data",
    "cvv.loadingConfig": "Loading detection configuration...",
    "cvv.loadingConfigDesc": "Please wait, loading available detection modes and channel information",
    "cvv.configLoadFailed": "Configuration load failed",
    "cvv.reload": "Reload",
    "cvv.maintenance": "Under Maintenance",
    "cvv.stopRequestFailed": "Stop detection request failed",
    "cvv.systemStatus": "System Status",
    "cvv.detectionService": "Detection Service",
    "cvv.channelStatus": "Channel Status",
    "cvv.detectionProgress": "Detection Progress",
    "cvv.channelUsers": "Users Using This Channel",
    "cvv.people": "people",
    "cvv.channelInfo": "Channel Information",
    "cvv.channelIdLabel": "Channel ID",
    "cvv.channel": "Channel",
    "cvv.waitingForCancel": "Waiting for cancellation to complete...",
    "cvv.stopping": "Stopping...",
    "cvv.usingMode": "Using Mode",
    "cvv.stopDetection": "Stop Detection",
    "cvv.detectingCVVs": "Detecting CVVs",
    "cvv.noCVVsCurrentlyDetecting": "No CVVs currently detecting",
    "cvv.moreCVVsDetecting": "More CVVs are detecting",
    "cvv.progress": "Progress",
    "cvv.consumedMCoin": "Consumed M Coins",
    "cvv.autoStopSet": "Auto Stop Set",
    "cvv.selectChannelFirst": "Please select a detection channel first",
    "cvv.detectionPassed": "Detection Passed",
    "cvv.detectionFailed": "Detection Failed",
    "cvv.cannotDetermine": "Cannot Determine",
    "cvv.noDataForStatus": "No {status} data",
    "cvv.copyAll": "Copy All",
    "cvv.items": "items",
    "cvv.detectionResults": "Detection Results",
    "cvv.totalConsumption": "Total Consumption",
    "cvv.taskId": "Task ID",
    "cvv.copyTaskId": "Copy Task ID",
    "cvv.mCoinsUnit": "M Coins",
    "cvv.detectionStatistics": "Detection Statistics",
    "cvv.completionTime": "Completion Time",
    "cvv.newDetection": "New Detection",
    "cvv.resetting": "Resetting...",
    "cvv.validTab": "Valid",
    "cvv.invalidTab": "Invalid",
    "cvv.unknownTab": "Unknown",
    "cvv.validStatus": "Valid",
    "cvv.invalidStatus": "Invalid",
    "cvv.unknownStatus": "Unknown",
    "cvv.retest": "Retest",
    "cvv.stepConfig": "Configuration",
    "cvv.stepInput": "CVV Input",
    "cvv.stepPrecheck": "Precheck",
    "cvv.stepDetecting": "Detecting",
    "cvv.stepResults": "Results",
    "cvv.statusOnline": "Online",
    "cvv.statusBusy": "Busy",
    "cvv.statusCrowded": "Crowded",
    "cvv.statusOffline": "Offline",
    "cvv.detectionCompleted": "Detection Completed",
    "cvv.detectionCompletedDesc": "Your CVV detection has been completed. Click the button below to view the detection results.",
    "cvv.viewResults": "View Results",
    "cvv.detectionInProgress": "Detection In Progress",
    "cvv.detectionInProgressDesc": "Your CVV detection is in progress. Click the button below to view real-time progress.",
    "cvv.viewProgress": "View Progress",
    "cvv.loadingProgress": "Loading progress data...",
    "cvv.loadingResults": "Loading result data...",
    "cvv.channel1": "Channel 1",
    "cvv.channel2": "Channel 2",
    "cvv.channel3": "Channel 3",
    "cvv.channel4": "Channel 4",
    "cvv.channel5": "Channel 5",
    "cvv.speedFast": "Fast",
    "cvv.speedMedium": "Medium",
    "cvv.speedSlow": "Slow",
    "cvv.speedVeryFast": "Very Fast",
    "cvv.channel1Desc": "High success rate channel, suitable for large batch detection",
    "cvv.channel2Desc": "Stable channel, balancing speed and accuracy",
    "cvv.channel3Desc": "Low consumption channel, suitable for precise detection",
    "cvv.channel4Desc": "High-speed channel, suitable for urgent detection",
    "cvv.channel5Desc": "Backup channel, stable and reliable",
    "cvv.footer.title": "CVV Intelligent Detection",
    "cvv.footer.description": "Professional CVV verification system using multi-channel detection technology, providing efficient and accurate credit card verification services, supporting real-time detection and batch processing.",
    "cvv.footer.coreFeatures": "Core Features",
    "cvv.footer.multiChannelDetection": "Multi-channel Intelligent Detection",
    "cvv.footer.realTimeFeedback": "Real-time Verification Feedback",
    "cvv.footer.batchProcessing": "Batch Data Processing",
    "cvv.footer.autoStopControl": "Auto Stop Control",
    "cvv.footer.security": "Security",
    "cvv.footer.sslEncryption": "SSL Encryption",
    "cvv.footer.dataProtection": "Data Protection",
    "cvv.footer.privacySecurity": "Privacy Security",
    "cvv.footer.realTimeMonitoring": "Real-time Monitoring",
    "cvv.footer.riskControl": "Risk Control",
    "cvv.footer.complianceDetection": "Compliance Detection",
    "cvv.footer.securityStandard": "Adopting bank-level security standards to ensure safe and reliable detection process",
    "cvv.footer.copyright": "© 2025 CVV Intelligent Detection System. All rights reserved.",
    "cvv.footer.detectionSpeed": "Detection Speed: Millisecond Response",
    "cvv.footer.accuracy": "Accuracy: 99.9%+",
    "cvv.footer.securityCertification": "Security Certified",

    // BIN Classify page
    "bin.title": "Card Classification",
    "bin.systemTitle": "Intelligent Card Classification System",
    "bin.systemSubtitle": "Efficient bank card classification tool based on BIN codes, supporting multi-dimensional intelligent analysis",
    "bin.subtitle": "Bank card BIN code classification and information query",
    "bin.inputLabel": "Enter Card Numbers",
    "bin.cardInputTitle": "Card Number Input",
    "bin.inputPlaceholder": "Enter card number information, one per line:\n\nSupported formats:\n1. Card number only: 4111111111111111\n2. Card number + date: 4111111111111111|12|25\n3. Card number + date + CVV: 4111111111111111|12|25|123\n4. Complete information: 4111111111111111|12|25|123|......\n\nSupports major card organizations: Visa, Mastercard, Amex, Discover, JCB, UnionPay, etc.",
    "bin.inputRecords": "Entered {count} records",
    "bin.batchProcessing": "Batch processing supported",
    "bin.queryButton": "Query Card Information",
    "bin.querying": "Querying...",
    "bin.dataSourceTitle": "Data Source Information",
    "bin.dataSource": "Data Source",
    "bin.dataSourceDesc": "From international card organizations (Visa, Mastercard, UnionPay, Amex, etc.) and major issuing bank internal data, combined with multiple payment networks and bank verification data.",
    "bin.dataAccuracy": "Data Accuracy",
    "bin.dataAccuracyDesc": "Through multiple verification mechanisms and user feedback systems, ensuring BIN information recognition accuracy up to",
    "bin.dataUpdate": "Data Update",
    "bin.dataUpdateDesc": "Automatically synchronized and updated daily, ensuring real-time and authoritative information.",
    "bin.realTimeUpdate": "Real-time Update",
    "bin.filterLabel": "Filter Conditions",
    "bin.filterAll": "All",
    "bin.filterCredit": "Credit Card",
    "bin.filterDebit": "Debit Card",
    "bin.filterPrepaid": "Prepaid Card",
    "bin.classifyButton": "Start Classification",
    "bin.results": "Classification Results",
    "bin.cardType": "Card Type",
    "bin.bank": "Issuing Bank",
    "bin.country": "Country",
    "bin.brand": "Card Brand",
    "bin.level": "Card Level",
    "bin.cardCopied": "Card number copied to clipboard",
    "bin.copyFailed": "Copy failed, please copy manually",
    "bin.cardsCopied": "Copied {count} card numbers to clipboard",
    "bin.filtering": "Filtering data...",
    "bin.categoryLabels.brand": "Card Brand",
    "bin.categoryLabels.type": "Card Type",
    "bin.categoryLabels.level": "Card Level",
    "bin.categoryLabels.bank": "Issuing Bank",
    "bin.categoryLabels.country": "Issuing Country",
    "bin.categoryLabels.product": "Product Name",
    "bin.footer.brandTitle": "Intelligent Card Analysis",
    "bin.footer.brandDesc": "Efficient bank card classification tool based on BIN codes, supporting multi-dimensional intelligent analysis, providing accurate and reliable card information identification services.",
    "bin.footer.coreFeatures": "Core Features",
    "bin.footer.multiDimensionClassification": "Multi-dimensional Intelligent Classification",
    "bin.footer.realTimeBINQuery": "Real-time BIN Information Query",
    "bin.footer.batchDataProcessing": "Batch Data Processing",
    "bin.footer.accuracyRate": "99.9% Recognition Accuracy",
    "bin.footer.globalSupport": "Global Support",
    "bin.footer.globalSupportDesc": "Supports major global card organizations, covering 200+ countries and regions",
    "bin.footer.copyright": "© 2025 Intelligent Card Analysis System. All rights reserved.",
    "bin.footer.dataUpdate": "Data Update: Real-time Sync",
    "bin.footer.serviceStatus": "Service Status: Normal Operation",
    "bin.footer.online": "Online",
    "bin.filter.title": "Multi-dimensional Filter",
    "bin.filter.newQuery": "New Query",
    "bin.filter.statistics": "Statistics",
    "bin.filter.query": "Query:",
    "bin.filter.filtered": "Filtered:",
    "bin.filter.total": "Total:",
    "bin.filter.classification": "Classification:",
    "bin.filter.mainCategory": "Main Category",
    "bin.filter.addFilter": "Add Filter Condition",
    "bin.filter.currentFilters": "Current Filter Conditions:",
    "bin.filter.select": "Select...",
    "bin.filter.all": "All",
    "bin.filter.addFilterHint": "Add filter conditions to filter card results",
    "bin.results.classifiedBy": "Results Classified by {category}",
    "bin.results.groups": "{count} groups",
    "bin.results.filtering": "Filtering...",
    "bin.results.selected": "Selected: {name} ({count} cards)",

    // BIN Classify Feature Page
    "binFeature.hero.title": "Card Classification",
    "binFeature.hero.subtitle": "Accurately identify bank card BIN codes, providing detailed issuer, card type, country and other information classification",
    "binFeature.features.title": "Core Features",
    "binFeature.features.subtitle": "Powerful bank card classification features to meet all your needs",
    "binFeature.features.accuracy.title": "Accurate Identification",
    "binFeature.features.accuracy.desc": "Based on official data from international card organizations, accurately identify BIN codes and provide detailed information such as issuer, card type, and country",
    "binFeature.features.details.title": "Detailed Information",
    "binFeature.features.details.desc": "Provides multi-dimensional classification information including card brand, type, level, issuing bank, issuing country, and product name",
    "binFeature.features.batch.title": "Batch Processing",
    "binFeature.features.batch.desc": "Supports batch input and processing, quickly classifying large amounts of card data to improve work efficiency",
    "binFeature.features.realtime.title": "Real-time Results",
    "binFeature.features.realtime.desc": "Returns classification results in real-time, supports multi-dimensional filtering and export for convenient data management",
    "binFeature.useCases.title": "Use Cases",
    "binFeature.useCases.subtitle": "Applicable to various business scenarios",
    "binFeature.useCases.management.title": "Card Management",
    "binFeature.useCases.management.desc": "Help financial institutions and payment platforms quickly identify and manage large amounts of card data",
    "binFeature.useCases.analysis.title": "Data Analysis",
    "binFeature.useCases.analysis.desc": "Perform data analysis and report generation through card classification information to support business decisions",
    "binFeature.useCases.risk.title": "Risk Control",
    "binFeature.useCases.risk.desc": "Identify and control risks based on card type and country information to enhance security",
    "binFeature.advantages.title": "Technical Advantages",
    "binFeature.advantages.subtitle": "Professional and reliable technical support",
    "binFeature.advantages.accuracy.title": "High Accuracy",
    "binFeature.advantages.accuracy.desc": "99.9% recognition accuracy with authoritative and reliable data sources",
    "binFeature.advantages.speed.title": "Fast Response",
    "binFeature.advantages.speed.desc": "Millisecond response time with strong batch processing capability",
    "binFeature.advantages.coverage.title": "Global Coverage",
    "binFeature.advantages.coverage.desc": "Supports major global card organizations, covering 200+ countries and regions",
    "binFeature.cta.title": "Start Using Now",
    "binFeature.cta.subtitle": "Experience professional card classification services and improve your work efficiency",
    "binFeature.cta.startButton": "Get Started",
    "binFeature.cta.backButton": "Back to Home",

    // CVV Check Feature Page
    "cvvFeature.hero.title": "CVV Batch Detection",
    "cvvFeature.hero.subtitle": "Professional CVV batch detection tool with multiple detection modes and channel selection",
    "cvvFeature.features.title": "Core Features",
    "cvvFeature.features.subtitle": "Powerful CVV detection features to meet all your needs",
    "cvvFeature.features.batch.title": "Batch Detection",
    "cvvFeature.features.batch.desc": "Supports batch input and processing, quickly detecting large amounts of CVV data to improve work efficiency",
    "cvvFeature.features.modes.title": "Multiple Modes",
    "cvvFeature.features.modes.desc": "Supports test mode, fast detection, backup detection and other modes to meet different scenario needs",
    "cvvFeature.features.channels.title": "Channel Selection",
    "cvvFeature.features.channels.desc": "Provides multiple detection channels, supports different speed and accuracy options for flexible detection strategy configuration",
    "cvvFeature.features.realtime.title": "Real-time Feedback",
    "cvvFeature.features.realtime.desc": "Real-time display of detection progress and results, supports automatic stop control for convenient monitoring and management",
    "cvvFeature.useCases.title": "Use Cases",
    "cvvFeature.useCases.subtitle": "Applicable to various business scenarios",
    "cvvFeature.useCases.verification.title": "Card Verification",
    "cvvFeature.useCases.verification.desc": "Help financial institutions and payment platforms quickly verify the validity of large amounts of cards",
    "cvvFeature.useCases.risk.title": "Risk Control",
    "cvvFeature.useCases.risk.desc": "Identify invalid cards through batch detection to effectively reduce business risks and losses",
    "cvvFeature.useCases.management.title": "Data Management",
    "cvvFeature.useCases.management.desc": "Batch detection and management of card data, supports result export and extraction code generation",
    "cvvFeature.advantages.title": "Technical Advantages",
    "cvvFeature.advantages.subtitle": "Professional and reliable technical support",
    "cvvFeature.advantages.accuracy.title": "High Accuracy",
    "cvvFeature.advantages.accuracy.desc": "99.9%+ detection accuracy with authoritative and reliable data sources",
    "cvvFeature.advantages.speed.title": "Fast Response",
    "cvvFeature.advantages.speed.desc": "Millisecond response time with support for high-concurrency batch processing",
    "cvvFeature.advantages.security.title": "Secure and Reliable",
    "cvvFeature.advantages.security.desc": "Adopts bank-level security standards, SSL encryption transmission to ensure data security",
    "cvvFeature.cta.title": "Start Using Now",
    "cvvFeature.cta.subtitle": "Experience professional CVV detection services and improve your work efficiency",
    "cvvFeature.cta.startButton": "Get Started",
    "cvvFeature.cta.backButton": "Back to Home",

    // BIN Query Feature Page
    "binQueryFeature.hero.title": "BIN Query",
    "binQueryFeature.hero.subtitle": "Fast BIN code query service to get detailed card and bank information",
    "binQueryFeature.features.title": "Core Features",
    "binQueryFeature.features.subtitle": "Powerful BIN query features to meet all your needs",
    "binQueryFeature.features.fast.title": "Fast Query",
    "binQueryFeature.features.fast.desc": "Real-time BIN code information query, millisecond response speed, quickly get card and bank data",
    "binQueryFeature.features.details.title": "Detailed Information",
    "binQueryFeature.features.details.desc": "Provides detailed information including card brand, type, level, issuing bank, issuing country, and product name",
    "binQueryFeature.features.bank.title": "Bank Data",
    "binQueryFeature.features.bank.desc": "Includes complete bank information such as bank name, website, and contact phone for business integration",
    "binQueryFeature.features.accuracy.title": "Accurate and Reliable",
    "binQueryFeature.features.accuracy.desc": "Based on official data from international card organizations, accurately identify BIN codes and provide authoritative information",
    "binQueryFeature.useCases.title": "Use Cases",
    "binQueryFeature.useCases.subtitle": "Applicable to various business scenarios",
    "binQueryFeature.useCases.verification.title": "Card Verification",
    "binQueryFeature.useCases.verification.desc": "Help payment platforms and financial institutions quickly verify card information, identify card type and issuing bank",
    "binQueryFeature.useCases.analysis.title": "Data Analysis",
    "binQueryFeature.useCases.analysis.desc": "Perform data analysis and report generation through BIN code queries to support business decisions and market research",
    "binQueryFeature.useCases.integration.title": "System Integration",
    "binQueryFeature.useCases.integration.desc": "Provides API interface for easy integration into existing systems, supports batch queries and automated processing",
    "binQueryFeature.advantages.title": "Technical Advantages",
    "binQueryFeature.advantages.subtitle": "Professional and reliable technical support",
    "binQueryFeature.advantages.speed.title": "Fast Response",
    "binQueryFeature.advantages.speed.desc": "Millisecond response time, real-time query results to improve user experience",
    "binQueryFeature.advantages.accuracy.title": "High Accuracy",
    "binQueryFeature.advantages.accuracy.desc": "99.9%+ query accuracy with authoritative and reliable data sources, continuously updated",
    "binQueryFeature.advantages.coverage.title": "Global Coverage",
    "binQueryFeature.advantages.coverage.desc": "Supports major global card organizations and banks, covering 200+ countries and regions",
    "binQueryFeature.cta.title": "Start Using Now",
    "binQueryFeature.cta.subtitle": "Experience professional BIN query services and improve your work efficiency",
    "binQueryFeature.cta.startButton": "Get Started",
    "binQueryFeature.cta.backButton": "Back to Home",
    "bin.results.clearSelection": "Clear Selection",
    "bin.results.exportData": "Export Data",
    "bin.results.cards": "cards",
    "bin.results.clickToView": "Click to view details of {count} cards",
    "bin.results.moreCards": "{count} more cards...",
    "bin.results.contains": "Contains {count} cards",
    "bin.results.copyAllCards": "Copy All Card Numbers",
    "bin.results.cardList": "Card List",
    "bin.results.noDetails": "No details available",
    "bin.results.cardsCount": "{count} cards",

    // Card Extract page
    "extract.title": "Card Information Extraction",
    "extract.subtitle": "Get bank card information through extraction code",
    "extract.codeLabel": "Extraction Code",
    "extract.codePlaceholder": "Enter extraction code",
    "extract.verifyCodeLabel": "Data Verification Code",
    "extract.verifyCodePlaceholder": "Enter verification code",
    "extract.extractButton": "Extract Information",
    "extract.remainingAttempts": "Remaining attempts today: {count}",
    "extract.noAttempts": "No attempts remaining today",
    "extract.success": "Extraction successful!",
    "extract.failed": "Extraction failed, please check extraction code or verification code",
    "extract.cardInfo": "Card Information",
    "extract.cardCount": "Card Count",
    "extract.detectionTime": "Detection Time",
    "extract.dataSource": "Data Source",

    // BIN Query page
    "binQuery.title": "BIN Query System",
    "binQuery.description": "Enter bank card BIN code to query detailed card information",
    "binQuery.queryTab": "BIN Query",

    "binQuery.refreshing": "Refreshing...",
    "binQuery.refresh": "Refresh",
    "binQuery.pageInfo": "Page",
    "binQuery.totalRecords": "records",
    "binQuery.previousPage": "Previous",
    "binQuery.nextPage": "Next",
    "binQuery.binLabel": "BIN Code",
    "binQuery.binInputLabel": "Enter BIN Code",
    "binQuery.binPlaceholder": "Enter 6-8 digit BIN code, e.g.: 412345",
    "binQuery.queryButton": "Query",
    "binQuery.querying": "Querying",
    "binQuery.tip1": "• BIN code is a bank identification number, usually the first 6-8 digits of the card number",
    "binQuery.tip2": "• Can query detailed information such as card type, brand, issuer, etc.",
    "binQuery.tip3": "• Supports mainstream cards like Visa, MasterCard, American Express, etc.",
    "binQuery.success": "Query successful!",
    "binQuery.failed": "Query failed, please check BIN code",
    "binQuery.cardType": "Card Type",
    "binQuery.cardBrand": "Card Brand",
    "binQuery.cardLevel": "Card Level",
    "binQuery.bankName": "Bank Name",
    "binQuery.country": "Country",
    "binQuery.currency": "Currency",
    "binQuery.website": "Bank Website",
    "binQuery.phone": "Bank Phone",
    "binQuery.results": "Query Results",
    "binQuery.queryTime": "Query Time",
    "binQuery.status.success": "Success",
    "binQuery.status.failed": "Failed",
    "binQuery.status.notFound": "Not Found",
    "binQuery.footer.title": "BIN Code Query",
    "binQuery.footer.description": "Professional bank identification code query tool, providing accurate card basic information and detailed attributes, supporting real-time query and batch processing.",
    "binQuery.footer.queryCapabilities": "Query Capabilities",
    "binQuery.footer.cardBrandRecognition": "Card Brand Recognition",
    "binQuery.footer.issuerInfo": "Issuer Information",
    "binQuery.footer.cardTypeDetection": "Card Type Detection",
    "binQuery.footer.countryRecognition": "Country/Region Recognition",
    "binQuery.footer.technicalSupport": "Technical Support",
    "binQuery.footer.querySpeed": "Query Speed",
    "binQuery.footer.dataAccuracy": "Data Accuracy",
    "binQuery.footer.binRange": "Supported BIN Range",
    "binQuery.footer.copyright": "© 2025 BIN Query System. Professional Bank Identification Code Query Service.",
    "binQuery.footer.responseTime": "Response Time: Real-time",
    "binQuery.footer.database": "Database: Latest",
    "binQuery.footer.serviceNormal": "Service Normal",

    // Info Generate page
    "info.title": "Information Generation",
    "info.systemTitle": "Smart Information Generation System",
    "info.subtitle": "Generate complete identity information based on card numbers using real geographic location data",
    "info.inputCardTitle": "Card Number Input",
    "info.inputLabel": "Enter card numbers (one per line)",
    "info.inputPlaceholder": "Enter card numbers, one per line\nExample:\n4147202688856879\n4207670137072792",
    "info.generateButton": "Start Generation",
    "info.generating": "Generating...",
    "info.costPreview": "Cost Preview",
    "info.detectedCards": "Detected {count} card numbers, will consume {cost} M coins",
    "info.costHint": "Will consume {count} M coins",
    "info.costPerCard": "Each generation consumes {price} M coins",
    "info.usingRealData": "Generate using real geographic location data",
    "info.supportBatch": "Supports batch generation, one card number per line",
    "info.results": "Generation Results",
    "info.resultsCount": "Generation Results ({count})",
    "info.exportCSV": "Export CSV",
    "info.noData": "No generated data",
    "info.noDataHint": "Enter card numbers and click generate to start",
    "info.name": "Name",
    "info.country": "Country",
    "info.province": "Province/State",
    "info.city": "City",
    "info.street": "Street",
    "info.zipCode": "Zip Code",
    "info.phone": "Phone",
    "info.email": "Email",
    "info.address": "Address",
    "info.expiry": "Expiry",
    "info.cardNumber": "Card Number",
    "info.generateComplete": "Generation Complete",
    "info.resultStats": "Information Generation Result Statistics",
    "info.successCount": "Successfully Generated",
    "info.failedCount": "Generation Failed",
    "info.actualCost": "Actual Cost",
    "info.failedCards": "Failed Card Numbers",
    "info.failedCardsTitle": "Failed Card Numbers",
    "info.copyAll": "Copy All",
    "info.close": "Close",
    "info.viewResults": "View Results",
    "info.copied": "Information copied to clipboard",
    "info.copyFailed": "Copy failed",
    "info.failedCardsCopied": "Failed card numbers copied to clipboard",
    "info.loginRequired": "Please login first",
    "info.enterCardNumber": "Please enter card number",
    "info.enterValidCard": "Please enter valid card numbers",
    "info.generateFailed": "Generation failed",
    "info.generateError": "Generation failed, please try again later",
    "info.footer.brandTitle": "Intelligent Information Generation",
    "info.footer.brandDesc": "An intelligent identity information generation tool based on real personal information and real geographic location data, providing you with complete and accurate personal information data.",
    "info.footer.coreFeatures": "Core Features",
    "info.footer.realPersonalInfo": "Real personal information",
    "info.footer.realLocation": "Real geographic location",
    "info.footer.completeIdentity": "Complete identity information generation",
    "info.footer.batchProcessing": "Batch data processing",
    "info.footer.csvExport": "CSV format export",
    "info.footer.supportedRegions": "Supported Regions",
    "info.footer.country.usa": "USA",
    "info.footer.country.uk": "UK",
    "info.footer.country.canada": "Canada",
    "info.footer.country.australia": "Australia",
    "info.footer.country.germany": "Germany",
    "info.footer.country.france": "France",
    "info.footer.regionsDesc": "Supports 200+ countries and regions, providing real personal information and geographic location data",
    "info.footer.copyright": "© 2025 Intelligent Information Generation System. All rights reserved.",
    "info.footer.dataSource": "Data source: Real geographic database",
    "info.footer.generationSpeed": "Generation speed: Millisecond response",
    "info.footer.safeReliable": "Safe and reliable",

    // Recharge page
    "recharge.pageTitle": "Recharge",
    "recharge.pageSubtitle": "Purchase M coins with USDT, enjoy more features and discounts",
    "recharge.title": "Account Recharge",
    "recharge.subtitle": "Recharge M coins to your account",
    "recharge.currentBalance": "Current Balance",
    "recharge.coins": "M Coins",
    "recharge.selectAmount": "Select Recharge Amount",
    "recharge.customAmount": "Custom Amount",
    "recharge.customPlaceholder": "Enter recharge amount",
    "recharge.paymentMethod": "Payment Method",
    "recharge.usdt": "USDT Payment",
    "recharge.packagesTab": "Package Recharge",
    "recharge.exchangeCode": "Exchange Code",
    "recharge.exchangeCodePlaceholder": "Please enter your exchange code",
    "recharge.exchangeCodeRecharge": "Exchange Code Recharge",
    "recharge.loadingPackages": "Loading recharge packages...",
    "recharge.noPackages": "No recharge packages available",
    "recharge.contactSupport": "Please contact customer service or try again later",
    "recharge.popular": "Popular",
    "recharge.selectPackage": "Select Package",
    "recharge.saveAmount": "Save",
    "recharge.processing": "Processing...",
    "recharge.instructions": "Instructions",
    "recharge.exchangeCodeDesc": "Exchange codes are usually obtained from promotions or campaigns. Each code can only be used once. M coins will be credited immediately after successful exchange.",
    "recharge.paymentDialogTitle": "USDT Payment",
    "recharge.paymentDialogDesc": "Please scan the QR code with your USDT wallet or transfer to the specified address",
    "recharge.purchaseAmount": "Purchase Amount:",
    "recharge.paymentAmount": "Payment Amount:",
    "recharge.timeLeft": "Time Left:",
    "recharge.discount": "Discount:",
    "recharge.orderNumber": "Order Number:",
    "recharge.generatingQR": "Generating QR code...",
    "recharge.scanQRCode": "Scan QR code with USDT wallet to pay",
    "recharge.walletAddress": "USDT Wallet Address (TRC20)",
    "recharge.addressCopied": "Address copied to clipboard",
    "recharge.paymentInstructions": "Payment Instructions:",
    "recharge.cancel": "Cancel",
    "recharge.paymentCompleted": "I have completed payment",
    "recharge.checkingPayment": "Checking Payment Status",
    "recharge.checkingPaymentDesc": "Contacting payment system to verify your transfer...",
    "recharge.verificationTime": "Verification may take up to 10 minutes",
    "recharge.doNotClose": "Please do not close this window, the system is processing your payment",
    "recharge.confirmCancel": "Confirm Cancel Payment",
    "recharge.confirmCancelDesc": "Are you sure you want to cancel the current payment order?",
    "recharge.cancelNotice": "Notice:",
    "recharge.cancelNotice1": "You will not be able to continue using the current payment address after cancellation",
    "recharge.cancelNotice2": "If you have already transferred, please do not cancel",
    "recharge.cancelNotice3": "You will need to select a package again for payment after cancellation",
    "recharge.continuePayment": "Continue Payment",
    "recharge.cancelling": "Cancelling...",
    "recharge.confirmCancelBtn": "Confirm Cancel",
    "recharge.operationSuccess": "Operation Successful",
    "recharge.paymentProcessing": "Payment Processing",
    "recharge.operationFailed": "Operation Failed",
    "recharge.addedToAccount": "Added to your account",
    "recharge.processingPayment": "System is processing your payment, please wait patiently",
    "recharge.retryOrContact": "Please retry or contact customer service",
    "recharge.close": "Close",
    "recharge.continueRecharge": "Continue Recharge",
    "recharge.retryWait": "Click to retry, continue waiting",
    "recharge.retry": "Retry",
    "recharge.rechargeButton": "Recharge Now",
    "recharge.useExchangeCode": "Use Exchange Code",
    "recharge.success": "Recharge successful!",
    "recharge.failed": "Recharge failed",
    "recharge.exchangeSuccess": "Exchange successful!",
    "recharge.exchangeFailed": "Exchange failed, please check exchange code",
    "recharge.paymentExpired": "Payment time has expired, please select a package again",
    "recharge.successMessage": "Recharge successful! M coins have been credited",
    "recharge.failedMessage": "Recharge failed, please check payment information or contact customer service",
    "recharge.retryMessage": "Recharge failed, please try again later",
    "recharge.exchangeSuccessMessage": "Exchange successful! M coins have been credited",
    "recharge.paymentPending": "Payment is being processed, please wait...",
    "recharge.paymentVerifyFailed": "Payment verification failed. If you have already paid, please contact customer service, or select a package again for payment.",
    "recharge.requestTimeout": "Request timeout, please click retry to continue checking payment status",
    "recharge.checkTimeout": "Payment check timeout, please click retry",
    "recharge.networkError": "Network error, please check your network connection and try again",
    "recharge.pleaseLogin": "Please login first",
    "recharge.footer.serviceTitle": "M Coin Recharge Service",
    "recharge.footer.serviceDesc": "Secure and convenient USDT recharge service with multiple package options, enjoy professional features and discounts, supports fast recharge with exchange codes.",
    "recharge.footer.advantages": "Recharge Advantages",
    "recharge.footer.packageOptions": "Multiple Package Options",
    "recharge.footer.discounts": "Discount Promotions",
    "recharge.footer.instantCredit": "Instant Credit Service",
    "recharge.footer.exchangeCode": "Exchange Code Support",
    "recharge.footer.security": "Security Guarantee",
    "recharge.footer.paymentMethod": "Payment Method",
    "recharge.footer.creditTime": "Credit Time",
    "recharge.footer.instant": "Instant Credit",
    "recharge.footer.securityLevel": "Security Level",
    "recharge.footer.bankLevel": "Bank-Level",
    "recharge.footer.copyright": "© 2025 M Coin Recharge System. Secure and reliable digital currency recharge service.",
    "recharge.footer.ssl": "SSL Encryption",
    "recharge.footer.instantProcessing": "Instant Processing",
    "recharge.footer.service247": "24/7 Service",

    // Account page
    "account.status.completed": "Completed",
    "account.status.pending": "Pending Payment",
    "account.status.processing": "Processing",
    "account.status.timeout": "Order Timeout",
    "account.status.failed": "Failed",
    "account.loginRequired": "Please login to view account information",
    "account.selectAvatar": "Select Avatar",
    "account.selectAvatarDesc": "Choose your favorite avatar style and variant from below",
    "account.currentSelection": "Current Selection",
    "account.realTimePreview": "Real-time Preview",
    "account.cancel": "Cancel",
    "account.saveAvatar": "Save Avatar",
    "account.saving": "Saving...",
    "account.editProfile": "Edit Profile",
    "account.activeUser": "Active User",
    "account.profile": "Profile",
    "account.rechargeRecords": "Recharge Records",
    "account.personalInfo": "Personal Information",
    "account.manageAccount": "Manage your account information and preferences",
    "account.username": "Username",
    "account.email": "Email Address",
    "account.changePassword": "Change Password",
    "account.newPasswordPlaceholder": "Enter new password (leave blank to keep unchanged)",
    "account.oldPassword": "Old Password",
    "account.newPassword": "New Password",
    "account.confirmNewPassword": "Confirm New Password",
    "account.oldPasswordPlaceholder": "Enter your current password",
    "account.newPasswordPlaceholder2": "Enter new password (at least 6 characters)",
    "account.confirmPasswordPlaceholder": "Enter new password again",
    "account.changePasswordDesc": "Change your login password",
    "account.changingPassword": "Changing...",
    "account.passwordChangeSuccess": "Password Changed Successfully",
    "account.passwordChangeSuccessDesc": "Your password has been successfully changed. Please use your new password to log in.",
    "account.joinDate": "Join Date",
    "account.accountStatus": "Account Status",
    "account.normal": "Normal",
    "account.saveChanges": "Save Changes",
    "account.viewRechargeHistory": "View all your recharge transaction history",
    "account.dateRange": "Date Range",
    "account.export": "Export",
    "account.date": "Date",
    "account.orderNumber": "Order Number",
    "account.rechargeAmount": "Recharge Amount",
    "account.paymentAmount": "Payment Amount",
    "account.paymentMethod": "Payment Method",
    "account.status": "Status",
    "account.transactionHash": "Transaction Hash",
    "account.noRechargeRecords": "No recharge records",
    "account.saveSuccess": "Save Successful",
    "account.profileUpdated": "Your profile has been successfully updated.",
    "account.confirm": "Confirm",

    // Register page
    "register.title": "Create Account",
    "register.subtitle": "Register a new account to start using our services",
    "register.username": "Username",
    "register.usernamePlaceholder": "Enter your username",
    "register.email": "Email Address",
    "register.emailPlaceholder": "Enter your email",
    "register.password": "Password",
    "register.passwordPlaceholder": "Create a secure password",
    "register.confirmPassword": "Confirm Password",
    "register.confirmPasswordPlaceholder": "Enter password again",
    "register.passwordMismatch": "Passwords do not match",
    "register.passwordReq8Chars": "At least 8 characters",
    "register.passwordReqUppercase": "Contains uppercase letter",
    "register.passwordReqLowercase": "Contains lowercase letter",
    "register.passwordReqNumber": "Contains number",
    "register.agreeTerms": "I agree to the",
    "register.termsOfService": "Terms of Service",
    "register.and": "and",
    "register.privacyPolicy": "Privacy Policy",
    "register.registerButton": "Create Account",
    "register.creating": "Creating...",
    "register.registerSuccess": "Registration successful! Redirecting to login page...",
    "register.registerFailed": "Registration failed, please try again",
    "register.registerError": "An error occurred during registration",
    "register.backToRegister": "Back to Register",
    "register.hasAccount": "Already have an account?",
    "register.login": "Sign in now",

    // Language selector
    "language.chinese": "中文",
    "language.english": "English",

    // Common
    "common.loading": "Loading...",
    "common.error": "An error occurred",
    "common.success": "Operation successful",
    "common.cancel": "Cancel",
    "common.confirm": "Confirm",
    "common.close": "Close",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const { user, token, refreshUserInfo } = useAuth()
  const languageConfig = getLanguageConfig()
  const defaultLanguage = (languageConfig?.defaultLanguage === "zh" || languageConfig?.defaultLanguage === "en") 
    ? languageConfig.defaultLanguage as Language 
    : "zh"
  
  const [language, setLanguage] = useState<Language>(defaultLanguage)

  // 初始化语言设置：优先级：用户登录信息 > localStorage > 配置文件默认值
  useEffect(() => {
    let initialLanguage: Language = defaultLanguage
    
    // 优先使用用户的语言设置
    if (user?.language && (user.language === "zh" || user.language === "en")) {
      initialLanguage = user.language as Language
    } else {
      // 如果没有用户设置，尝试从localStorage读取
      const savedLanguage = localStorage.getItem("language") as Language
      if (savedLanguage && (savedLanguage === "zh" || savedLanguage === "en")) {
        initialLanguage = savedLanguage
      }
    }
    
    setLanguage(initialLanguage)
  }, [defaultLanguage, user?.language]) // 当用户信息加载后或默认语言变化时重新初始化

  // 监听用户登录/登出，应用用户的语言设置
  useEffect(() => {
    if (user?.language && (user.language === "zh" || user.language === "en")) {
      // 用户登录且有语言设置，应用用户的语言
      setLanguage(user.language as Language)
      // 同步到localStorage
      localStorage.setItem("language", user.language)
    }
    // 如果用户登出（user为null），保持当前语言设置（localStorage中已有）
  }, [user?.language]) // 监听user.language变化

  // 调用后端API更新语言设置
  const updateLanguageOnServer = async (lang: Language) => {
    if (!token) return false
    
    try {
      const response = await authenticatedRequest('/auth/language', token, {
        method: 'PUT',
        body: JSON.stringify({ language: lang })
      })
      
      if (response.success) {
        console.log('[LanguageProvider] 语言设置已同步到服务器')
        return true
      } else {
        console.error('[LanguageProvider] 更新语言设置失败:', response.message)
        return false
      }
    } catch (error) {
      console.error('[LanguageProvider] 更新语言设置错误:', error)
      return false
    }
  }

  const handleSetLanguage = async (lang: Language) => {
    // 更新本地状态
    setLanguage(lang)
    // 保存到localStorage
    localStorage.setItem("language", lang)
    
    // 如果用户已登录，同步到后端
    if (token && user) {
      const success = await updateLanguageOnServer(lang)
      if (success) {
        // 更新成功后，刷新用户信息以同步最新的language字段
        await refreshUserInfo()
      }
    }
  }

  const t = (key: string, params?: Record<string, string | number>): string => {
    let text = translations[language][key as keyof (typeof translations)[typeof language]] || key
    if (params) {
      Object.keys(params).forEach((paramKey) => {
        text = text.replace(new RegExp(`\\{${paramKey}\\}`, 'g'), String(params[paramKey]))
      })
    }
    return text
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
