"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "zh" | "en"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  zh: {
    // Navigation
    "nav.home": "首页",
    "nav.binClassify": "BIN分类",
    "nav.cvvCheck": "CVV检测",
    "nav.binQuery": "BIN查询",
    "nav.infoGenerate": "信息生成",

    "nav.recharge": "充值",
    "nav.login": "登录",
    "nav.register": "注册",

    // Home page
    "home.newBadge": "专业银行卡检测平台",
    "home.title": "银行卡检测",
    "home.titleHighlight": "专业可靠",
    "home.subtitle":
      "提供全面的银行卡有效性检测服务，包括BIN分类、CVV验证、卡信息提取等专业功能。安全、快速、准确的金融科技解决方案。",
    "home.startDetection": "开始检测",
    "home.learnMore": "了解更多",
    "home.cardValid": "有效",
    "home.detectionTime": "检测时间: 0.2秒",
    "home.stats.accuracy": "检测准确率",
    "home.stats.dailyChecks": "日检测量",
    "home.stats.responseTime": "平均响应时间",
    "home.stats.service": "全天候服务",
    "home.coreFeatures": "核心功能",
    "home.featuresSubtitle": "专业的银行卡检测服务，满足您的各种需求",
    "home.binClassify": "BIN分类",
    "home.binClassifyDesc": "精确识别银行卡BIN码，提供详细的发卡行、卡片类型、国家等信息分类。",
    "home.cvvCheck": "CVV批量检测",
    "home.cvvCheckDesc": "专业的CVV批量检测工具，支持多种检测模式和通道选择",
    "home.binQuery": "BIN查询",
    "home.binQueryDesc": "快速查询银行卡BIN码信息，获取详细的卡片和银行数据。",
    "home.learnMoreLink": "了解更多",
    "home.whyChoose": "为什么选择我们",
    "home.fastDetection": "极速检测",
    "home.fastDetectionDesc": "毫秒级响应，批量处理能力强",
    "home.highAccuracy": "高准确率",
    "home.highAccuracyDesc": "99.9%的检测准确率，数据可靠",
    "home.globalCoverage": "全球覆盖",
    "home.globalCoverageDesc": "支持全球主要银行卡类型",
    "home.testimonial": "专业可靠的银行卡检测服务，帮助我们大大提升了业务效率和数据准确性。",
    "home.testimonialAuthor": "— 金融科技公司 CTO",
    "home.ctaTitle": "开始使用专业银行卡检测服务",
    "home.ctaSubtitle": "立即体验我们的银行卡检测平台，提升您的业务效率",
    "home.freeTrial": "免费试用",
    "home.contactSupport": "联系客服",

    // Login page
    "login.welcome": "欢迎回来",
    "login.subtitle": "登录您的账户以继续使用",
    "login.email": "邮箱地址",
    "login.emailPlaceholder": "输入您的邮箱",
    "login.password": "密码",
    "login.passwordPlaceholder": "输入您的密码",
    "login.forgotPassword": "忘记密码？",
    "login.loginButton": "登录",
    "login.or": "或者",
    "login.noAccount": "还没有账户？",
    "login.register": "立即注册",
    "login.wechat": "微信",

    // CVV Check page
    "cvv.title": "CVV批量检测",
    "cvv.subtitle": "专业的CVV批量检测工具，支持多种检测模式和通道选择",
    "cvv.inputLabel": "输入银行卡信息",
    "cvv.inputPlaceholder": "请输入银行卡号，每行一条\n格式1：卡号|月|年|cvv\n格式2：卡号|月|年|cvv|其他",
    "cvv.detectButton": "开始检测",
    "cvv.costHint": "将消耗 {count} 个M币",
    "cvv.insufficientBalance": "余额不足，请先充值",
    "cvv.results": "检测结果",
    "cvv.cardNumber": "卡号",
    "cvv.cvvCode": "CVV码",
    "cvv.status": "状态",
    "cvv.valid": "有效",
    "cvv.invalid": "无效",
    "cvv.copy": "复制",
    "cvv.export": "导出CSV",
    "cvv.noResults": "暂无检测结果",
    "cvv.detectionConfig": "检测配置",
    "cvv.selectModeAndChannel": "选择检测模式和通道",
    "cvv.detectionMode": "检测模式",
    "cvv.selectChannel": "选择通道",
    "cvv.currentSelection": "当前选择",
    "cvv.consumption": "消耗",
    "cvv.mCoins": "m币",
    "cvv.speed": "速度",
    "cvv.description": "说明",
    "cvv.nextStepInput": "下一步：输入CVV",
    "cvv.inputTitle": "CVV输入",
    "cvv.currentConfig": "当前配置",
    "cvv.mode": "模式",
    "cvv.cvvList": "CVV列表",
    "cvv.previousStep": "上一步",
    "cvv.startPrecheck": "开始预检测",
    "cvv.prechecking": "预检测中",
    "cvv.formalChecking": "正式检测中",
    "cvv.startFormalCheck": "开始正式检测",
    "cvv.precheckResultsTitle": "预检测结果",
    "cvv.formatVerificationComplete": "格式验证完成",
    "cvv.budget": "预算",
    "cvv.estimatedConsumption": "预计消耗",
    "cvv.autoStopOptional": "自动停止（可选）",
    "cvv.autoStopPlaceholder": "输入有效数量",
    "cvv.autoStopDescription": "当检测到指定数量的有效CVV时自动停止检测",
    "cvv.precheckSuccess": "预检测成功",
    "cvv.noValidCVVs": "没有有效的CVV",
    "cvv.precheckFailed": "预检测失败",
    "cvv.allCVVsFormatCorrect": "所有CVV格式都正确",
    "cvv.returnToModify": "返回修改",
    "cvv.maxValid": "最大有效数",
    "cvv.systemStatus": "系统状态",
    "cvv.detectionService": "检测服务",
    "cvv.channelStatus": "通道状态",
    "cvv.detectionProgress": "检测进度",
    "cvv.usingMode": "使用模式",
    "cvv.stopDetection": "停止检测",
    "cvv.detectingCVVs": "正在检测的CVV",
    "cvv.noCVVsCurrentlyDetecting": "当前没有正在检测的CVV",
    "cvv.moreCVVsDetecting": "还有更多CVV正在检测中",
    "cvv.progress": "进度",
    "cvv.consumedMCoin": "已消耗M币",
    "cvv.autoStopSet": "已设置自动停止",
    "cvv.selectChannelFirst": "请先选择检测通道",
    "cvv.detectionPassed": "检测通过",
    "cvv.detectionFailed": "检测失败",
    "cvv.cannotDetermine": "无法确定",
    "cvv.noDataForStatus": "暂无{status}数据",
    "cvv.copyAll": "复制全部",
    "cvv.items": "条",
    "cvv.detectionResults": "检测结果",
    "cvv.totalConsumption": "总消耗",
    "cvv.validTab": "有效",
    "cvv.invalidTab": "无效",
    "cvv.unknownTab": "未知",
    "cvv.validStatus": "有效",
    "cvv.invalidStatus": "无效",
    "cvv.unknownStatus": "未知",
    "cvv.retest": "重新检测",
    "cvv.stepConfig": "配置选择",
    "cvv.stepInput": "CVV输入",
    "cvv.stepPrecheck": "预检测",
    "cvv.stepDetecting": "检测中",
    "cvv.stepResults": "检测结果",
    "cvv.statusOnline": "在线",
    "cvv.statusBusy": "繁忙",
    "cvv.statusOffline": "离线",
    "cvv.channel1": "通道1",
    "cvv.channel2": "通道2",
    "cvv.channel3": "通道3",
    "cvv.channel4": "通道4",
    "cvv.channel5": "通道5",
    "cvv.speedFast": "快速",
    "cvv.speedMedium": "中等",
    "cvv.speedSlow": "较慢",
    "cvv.speedVeryFast": "极快",
    "cvv.channel1Desc": "高成功率通道，适合大批量检测",
    "cvv.channel2Desc": "稳定通道，平衡速度与准确性",
    "cvv.channel3Desc": "低消耗通道，适合精准检测",
    "cvv.channel4Desc": "高速通道，适合紧急检测",
    "cvv.channel5Desc": "备用通道，稳定可靠",

    // BIN Classify page
    "bin.title": "BIN分类",
    "bin.subtitle": "银行卡BIN码分类和信息查询",
    "bin.inputLabel": "输入银行卡号",
    "bin.inputPlaceholder": "请输入完整的银行卡号，每行一个",
    "bin.filterLabel": "筛选条件",
    "bin.filterAll": "全部",
    "bin.filterCredit": "信用卡",
    "bin.filterDebit": "借记卡",
    "bin.filterPrepaid": "预付卡",
    "bin.classifyButton": "开始分类",
    "bin.results": "分类结果",
    "bin.cardType": "卡片类型",
    "bin.bank": "发卡银行",
    "bin.country": "国家",
    "bin.brand": "卡片品牌",
    "bin.level": "卡片等级",

    // Card Extract page
    "extract.title": "卡信息提取",
    "extract.subtitle": "通过提取码获取银行卡信息",
    "extract.codeLabel": "提取码",
    "extract.codePlaceholder": "请输入提取码",
    "extract.verifyCodeLabel": "数据验证码",
    "extract.verifyCodePlaceholder": "请输入验证码",
    "extract.extractButton": "提取信息",
    "extract.remainingAttempts": "今日剩余尝试次数：{count}",
    "extract.noAttempts": "今日尝试次数已用完",
    "extract.success": "提取成功！",
    "extract.failed": "提取失败，请检查提取码或验证码",
    "extract.cardInfo": "卡片信息",
    "extract.cardCount": "卡片数量",
    "extract.detectionTime": "检测时间",
    "extract.dataSource": "数据来源",

    // BIN Query page
    "binQuery.title": "BIN查询系统",
    "binQuery.description": "输入银行卡BIN码查询详细的卡片信息",
    "binQuery.queryTab": "BIN查询",

    "binQuery.refreshing": "刷新中...",
    "binQuery.refresh": "刷新",
    "binQuery.pageInfo": "第",
    "binQuery.totalRecords": "条记录",
    "binQuery.previousPage": "上一页",
    "binQuery.nextPage": "下一页",
    "binQuery.binLabel": "BIN码",
    "binQuery.binPlaceholder": "请输入6-8位BIN码",
    "binQuery.queryButton": "查询BIN",
    "binQuery.success": "查询成功！",
    "binQuery.failed": "查询失败，请检查BIN码",
    "binQuery.cardType": "卡片类型",
    "binQuery.cardBrand": "卡片品牌",
    "binQuery.cardLevel": "卡片等级",
    "binQuery.bankName": "发卡银行",
    "binQuery.country": "发卡国家",
    "binQuery.currency": "货币",
    "binQuery.website": "银行官网",
    "binQuery.phone": "银行电话",
    "binQuery.results": "查询结果",
    "binQuery.queryTime": "查询时间",
    "binQuery.status.success": "成功",
    "binQuery.status.failed": "失败",
    "binQuery.status.notFound": "未找到",

    // Info Generate page
    "info.title": "信息生成",
    "info.subtitle": "根据银行卡号生成完整的身份信息",
    "info.inputLabel": "输入银行卡号",
    "info.inputPlaceholder": "请输入银行卡号，每行一个",
    "info.generateButton": "生成信息",
    "info.costHint": "将消耗 {count} 个M币",
    "info.results": "生成结果",
    "info.name": "姓名",
    "info.country": "国家",
    "info.province": "省/州",
    "info.city": "城市",
    "info.street": "街道",
    "info.zipCode": "邮编",
    "info.phone": "电话",

    // Recharge page
    "recharge.title": "账户充值",
    "recharge.subtitle": "为您的账户充值M币",
    "recharge.currentBalance": "当前余额",
    "recharge.coins": "M币",
    "recharge.selectAmount": "选择充值金额",
    "recharge.customAmount": "自定义金额",
    "recharge.customPlaceholder": "输入充值金额",
    "recharge.paymentMethod": "支付方式",
    "recharge.usdt": "USDT支付",
    "recharge.exchangeCode": "兑换码",
    "recharge.exchangeCodePlaceholder": "输入兑换码",
    "recharge.rechargeButton": "立即充值",
    "recharge.useExchangeCode": "使用兑换码",
    "recharge.success": "充值成功！",
    "recharge.failed": "充值失败",
    "recharge.exchangeSuccess": "兑换成功！",
    "recharge.exchangeFailed": "兑换失败，请检查兑换码",

    // Account page
    "account.status.completed": "已完成",
    "account.status.failed": "失败",
    "account.status.pending": "处理中",

    // Register page
    "register.title": "创建账户",
    "register.subtitle": "注册新账户开始使用",
    "register.email": "邮箱地址",
    "register.emailPlaceholder": "输入您的邮箱",
    "register.password": "密码",
    "register.passwordPlaceholder": "输入您的密码",
    "register.confirmPassword": "确认密码",
    "register.confirmPasswordPlaceholder": "再次输入密码",
    "register.registerButton": "注册",
    "register.hasAccount": "已有账户？",
    "register.login": "立即登录",

    // Language selector
    "language.chinese": "中文",
    "language.english": "English",

    // Common
    "common.loading": "加载中...",
    "common.error": "发生错误",
    "common.success": "操作成功",
    "common.cancel": "取消",
    "common.confirm": "确认",
    "common.close": "关闭",
  },
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.binClassify": "BIN Classify",
    "nav.cvvCheck": "CVV Check",
    "nav.binQuery": "BIN Query",
    "nav.infoGenerate": "Info Generate",

    "nav.recharge": "Recharge",
    "nav.login": "Login",
    "nav.register": "Register",

    // Home page
    "home.newBadge": "Professional Card Detection Platform",
    "home.title": "Card Detection",
    "home.titleHighlight": "Professional & Reliable",
    "home.subtitle":
      "Comprehensive bank card validity detection services, including BIN classification, CVV verification, card information extraction and other professional functions. Secure, fast, and accurate fintech solutions.",
    "home.startDetection": "Start Detection",
    "home.learnMore": "Learn More",
    "home.cardValid": "Valid",
    "home.detectionTime": "Detection Time: 0.2s",
    "home.stats.accuracy": "Detection Accuracy",
    "home.stats.dailyChecks": "Daily Detections",
    "home.stats.responseTime": "Avg Response Time",
    "home.stats.service": "24/7 Service",
    "home.coreFeatures": "Core Features",
    "home.featuresSubtitle": "Professional bank card detection services to meet all your needs",
    "home.binClassify": "BIN Classification",
    "home.binClassifyDesc":
      "Accurately identify bank card BIN codes, providing detailed issuer, card type, country and other information classification.",
    "home.cvvCheck": "CVV Batch Detection",
    "home.cvvCheckDesc": "Professional CVV batch detection tool with multiple detection modes and channel selection",
    "home.binQuery": "BIN Query",
    "home.binQueryDesc":
      "Fast BIN code query service to get detailed card and bank information.",
    "home.learnMoreLink": "Learn More",
    "home.whyChoose": "Why Choose Us",
    "home.fastDetection": "Lightning Fast",
    "home.fastDetectionDesc": "Millisecond response with strong batch processing capability",
    "home.highAccuracy": "High Accuracy",
    "home.highAccuracyDesc": "99.9% detection accuracy with reliable data",
    "home.globalCoverage": "Global Coverage",
    "home.globalCoverageDesc": "Support for major bank card types worldwide",
    "home.testimonial":
      "Professional and reliable bank card detection service that has greatly improved our business efficiency and data accuracy.",
    "home.testimonialAuthor": "— CTO, Fintech Company",
    "home.ctaTitle": "Start Using Professional Card Detection Services",
    "home.ctaSubtitle": "Experience our bank card detection platform now and boost your business efficiency",
    "home.freeTrial": "Free Trial",
    "home.contactSupport": "Contact Support",

    // Login page
    "login.welcome": "Welcome Back",
    "login.subtitle": "Sign in to your account to continue",
    "login.email": "Email Address",
    "login.emailPlaceholder": "Enter your email",
    "login.password": "Password",
    "login.passwordPlaceholder": "Enter your password",
    "login.forgotPassword": "Forgot password?",
    "login.loginButton": "Sign In",
    "login.or": "or",
    "login.noAccount": "Don't have an account?",
    "login.register": "Sign up now",
    "login.wechat": "WeChat",

    // CVV Check page
    "cvv.title": "CVV Batch Detection",
    "cvv.subtitle": "Professional CVV batch detection tool with multiple detection modes and channel selection",
    "cvv.inputLabel": "Enter Card Information",
    "cvv.inputPlaceholder":
      "Enter card numbers, one per line\nFormat 1: CardNumber|Month|Year|CVV\nFormat 2: CardNumber|Month|Year|CVV|Other",
    "cvv.detectButton": "Start Detection",
    "cvv.costHint": "Will consume {count} M coins",
    "cvv.insufficientBalance": "Insufficient balance, please recharge first",
    "cvv.results": "Detection Results",
    "cvv.cardNumber": "Card Number",
    "cvv.cvvCode": "CVV Code",
    "cvv.status": "Status",
    "cvv.valid": "Valid",
    "cvv.invalid": "Invalid",
    "cvv.copy": "Copy",
    "cvv.export": "Export CSV",
    "cvv.noResults": "No detection results",
    "cvv.detectionConfig": "Detection Configuration",
    "cvv.selectModeAndChannel": "Select detection mode and channel",
    "cvv.detectionMode": "Detection Mode",
    "cvv.selectChannel": "Select Channel",
    "cvv.currentSelection": "Current Selection",
    "cvv.consumption": "Consumption",
    "cvv.mCoins": "M coins",
    "cvv.speed": "Speed",
    "cvv.description": "Description",
    "cvv.nextStepInput": "Next: Input CVV",
    "cvv.inputTitle": "CVV Input",
    "cvv.currentConfig": "Current Configuration",
    "cvv.mode": "Mode",
    "cvv.cvvList": "CVV List",
    "cvv.previousStep": "Previous Step",
    "cvv.startPrecheck": "Start Precheck",
    "cvv.prechecking": "Prechecking",
    "cvv.formalChecking": "Formal Detection",
    "cvv.startFormalCheck": "Start Formal Detection",
    "cvv.precheckResultsTitle": "Precheck Results",
    "cvv.formatVerificationComplete": "Format verification complete",
    "cvv.budget": "Budget",
    "cvv.estimatedConsumption": "Estimated consumption",
    "cvv.autoStopOptional": "Auto stop (optional)",
    "cvv.autoStopPlaceholder": "Enter valid count",
    "cvv.autoStopDescription": "Automatically stop detection when the specified number of valid CVVs is reached",
    "cvv.precheckSuccess": "Precheck Success",
    "cvv.noValidCVVs": "No valid CVVs",
    "cvv.precheckFailed": "Precheck Failed",
    "cvv.allCVVsFormatCorrect": "All CVVs format is correct",
    "cvv.returnToModify": "Return to Modify",
    "cvv.maxValid": "Max Valid",
    "cvv.systemStatus": "System Status",
    "cvv.detectionService": "Detection Service",
    "cvv.channelStatus": "Channel Status",
    "cvv.detectionProgress": "Detection Progress",
    "cvv.usingMode": "Using Mode",
    "cvv.stopDetection": "Stop Detection",
    "cvv.detectingCVVs": "Detecting CVVs",
    "cvv.noCVVsCurrentlyDetecting": "No CVVs currently detecting",
    "cvv.moreCVVsDetecting": "More CVVs are detecting",
    "cvv.progress": "Progress",
    "cvv.consumedMCoin": "Consumed M Coins",
    "cvv.autoStopSet": "Auto Stop Set",
    "cvv.selectChannelFirst": "Please select a detection channel first",
    "cvv.detectionPassed": "Detection Passed",
    "cvv.detectionFailed": "Detection Failed",
    "cvv.cannotDetermine": "Cannot Determine",
    "cvv.noDataForStatus": "No {status} data",
    "cvv.copyAll": "Copy All",
    "cvv.items": "items",
    "cvv.detectionResults": "Detection Results",
    "cvv.totalConsumption": "Total Consumption",
    "cvv.validTab": "Valid",
    "cvv.invalidTab": "Invalid",
    "cvv.unknownTab": "Unknown",
    "cvv.validStatus": "Valid",
    "cvv.invalidStatus": "Invalid",
    "cvv.unknownStatus": "Unknown",
    "cvv.retest": "Retest",
    "cvv.stepConfig": "Configuration",
    "cvv.stepInput": "CVV Input",
    "cvv.stepPrecheck": "Precheck",
    "cvv.stepDetecting": "Detecting",
    "cvv.stepResults": "Results",
    "cvv.statusOnline": "Online",
    "cvv.statusBusy": "Busy",
    "cvv.statusOffline": "Offline",
    "cvv.channel1": "Channel 1",
    "cvv.channel2": "Channel 2",
    "cvv.channel3": "Channel 3",
    "cvv.channel4": "Channel 4",
    "cvv.channel5": "Channel 5",
    "cvv.speedFast": "Fast",
    "cvv.speedMedium": "Medium",
    "cvv.speedSlow": "Slow",
    "cvv.speedVeryFast": "Very Fast",
    "cvv.channel1Desc": "High success rate channel, suitable for large batch detection",
    "cvv.channel2Desc": "Stable channel, balancing speed and accuracy",
    "cvv.channel3Desc": "Low consumption channel, suitable for precise detection",
    "cvv.channel4Desc": "High-speed channel, suitable for urgent detection",
    "cvv.channel5Desc": "Backup channel, stable and reliable",

    // BIN Classify page
    "bin.title": "BIN Classification",
    "bin.subtitle": "Bank card BIN code classification and information query",
    "bin.inputLabel": "Enter Card Numbers",
    "bin.inputPlaceholder": "Enter complete card numbers, one per line",
    "bin.filterLabel": "Filter Conditions",
    "bin.filterAll": "All",
    "bin.filterCredit": "Credit Card",
    "bin.filterDebit": "Debit Card",
    "bin.filterPrepaid": "Prepaid Card",
    "bin.classifyButton": "Start Classification",
    "bin.results": "Classification Results",
    "bin.cardType": "Card Type",
    "bin.bank": "Issuing Bank",
    "bin.country": "Country",
    "bin.brand": "Card Brand",
    "bin.level": "Card Level",

    // Card Extract page
    "extract.title": "Card Information Extraction",
    "extract.subtitle": "Get bank card information through extraction code",
    "extract.codeLabel": "Extraction Code",
    "extract.codePlaceholder": "Enter extraction code",
    "extract.verifyCodeLabel": "Data Verification Code",
    "extract.verifyCodePlaceholder": "Enter verification code",
    "extract.extractButton": "Extract Information",
    "extract.remainingAttempts": "Remaining attempts today: {count}",
    "extract.noAttempts": "No attempts remaining today",
    "extract.success": "Extraction successful!",
    "extract.failed": "Extraction failed, please check extraction code or verification code",
    "extract.cardInfo": "Card Information",
    "extract.cardCount": "Card Count",
    "extract.detectionTime": "Detection Time",
    "extract.dataSource": "Data Source",

    // BIN Query page
    "binQuery.title": "BIN Query System",
    "binQuery.description": "Enter bank card BIN code to query detailed card information",
    "binQuery.queryTab": "BIN Query",

    "binQuery.refreshing": "Refreshing...",
    "binQuery.refresh": "Refresh",
    "binQuery.pageInfo": "Page",
    "binQuery.totalRecords": "records",
    "binQuery.previousPage": "Previous",
    "binQuery.nextPage": "Next",
    "binQuery.binLabel": "BIN Code",
    "binQuery.binPlaceholder": "Enter 6-8 digit BIN code",
    "binQuery.queryButton": "Query BIN",
    "binQuery.success": "Query successful!",
    "binQuery.failed": "Query failed, please check BIN code",
    "binQuery.cardType": "Card Type",
    "binQuery.cardBrand": "Card Brand",
    "binQuery.cardLevel": "Card Level",
    "binQuery.bankName": "Bank Name",
    "binQuery.country": "Country",
    "binQuery.currency": "Currency",
    "binQuery.website": "Bank Website",
    "binQuery.phone": "Bank Phone",
    "binQuery.results": "Query Results",
    "binQuery.queryTime": "Query Time",
    "binQuery.status.success": "Success",
    "binQuery.status.failed": "Failed",
    "binQuery.status.notFound": "Not Found",

    // Info Generate page
    "info.title": "Information Generation",
    "info.subtitle": "Generate complete identity information based on card numbers",
    "info.inputLabel": "Enter Card Numbers",
    "info.inputPlaceholder": "Enter card numbers, one per line",
    "info.generateButton": "Generate Information",
    "info.costHint": "Will consume {count} M coins",
    "info.results": "Generation Results",
    "info.name": "Name",
    "info.country": "Country",
    "info.province": "Province/State",
    "info.city": "City",
    "info.street": "Street",
    "info.zipCode": "Zip Code",
    "info.phone": "Phone",

    // Recharge page
    "recharge.title": "Account Recharge",
    "recharge.subtitle": "Recharge M coins to your account",
    "recharge.currentBalance": "Current Balance",
    "recharge.coins": "M Coins",
    "recharge.selectAmount": "Select Recharge Amount",
    "recharge.customAmount": "Custom Amount",
    "recharge.customPlaceholder": "Enter recharge amount",
    "recharge.paymentMethod": "Payment Method",
    "recharge.usdt": "USDT Payment",
    "recharge.exchangeCode": "Exchange Code",
    "recharge.exchangeCodePlaceholder": "Enter exchange code",
    "recharge.rechargeButton": "Recharge Now",
    "recharge.useExchangeCode": "Use Exchange Code",
    "recharge.success": "Recharge successful!",
    "recharge.failed": "Recharge failed",
    "recharge.exchangeSuccess": "Exchange successful!",
    "recharge.exchangeFailed": "Exchange failed, please check exchange code",

    // Account page
    "account.status.completed": "Completed",
    "account.status.failed": "Failed",
    "account.status.pending": "Processing",

    // Register page
    "register.title": "Create Account",
    "register.subtitle": "Register a new account to get started",
    "register.email": "Email Address",
    "register.emailPlaceholder": "Enter your email",
    "register.password": "Password",
    "register.passwordPlaceholder": "Enter your password",
    "register.confirmPassword": "Confirm Password",
    "register.confirmPasswordPlaceholder": "Enter password again",
    "register.registerButton": "Register",
    "register.hasAccount": "Already have an account?",
    "register.login": "Sign in now",

    // Language selector
    "language.chinese": "中文",
    "language.english": "English",

    // Common
    "common.loading": "Loading...",
    "common.error": "An error occurred",
    "common.success": "Operation successful",
    "common.cancel": "Cancel",
    "common.confirm": "Confirm",
    "common.close": "Close",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("zh")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && (savedLanguage === "zh" || savedLanguage === "en")) {
      setLanguage(savedLanguage)
    }
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem("language", lang)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
